### ISSUE TITLE
Provide multiple Menas instances to DAO

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#1000]
## Background
Currently, `Standardization` and `Conformance` take in a single `Menas` URI, if that `Menas` instance fails the spark job will fail as well.

## Feature
To provide higher availability, in cases where the `Menas` URI is not pointing to a load-balancer, we can accept multiple `Menas` URIs and try them in sequence when any of them are non-responsive.

## Proposed Solution 
`menas.rest.uris="http://localhost:8080/menas/api,http://localhost:8081/menas/api"`

**Comment by lokm01** [comment]
How about looking at that stateless auth so that we can load balance with health checks etc?

**Comment by GeorgiChochov** [comment]
> How about looking at that stateless auth so that we can load balance with health checks etc?

I have looked at it, I can and will make it stateless. Postponed #92 for a next release because 1.3.0 included the dao module rewrite and it would have made it was a big enough change on its own for that release.
Turns out we won't be able to place a load-balancer any time soon, so we won't get to see the main benefit of #92.
We really need to have some fault tolerance, so this will allow us to achieve that and will even work alongside the benefits of #92 with or without an actual load-balancer.

**Comment by yruslan** [comment]
I agree that although having support for a load balancer in the future is great, the most important feature we need from a load balancer is fault tolerance, since we don't have much load.
And this feature adds a very helpful possibility to have fault-tolerance with a non-load-balanced setup.

**Comment by GeorgiChochov** [comment]
## For release notes:
`Standardization` and `Conformance` jobs can now run in a more fault-tolerant way, by specifying multiple `Menas URLs`. This can be done per environment in the `enceladus_env.sh` script.
