### ISSUE TITLE
Investigate how mapping rule can be made stream-friendly

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1017]
## Background
The current implementation of the mapping conformance rule uses array explosions and aggregations. This is not supported for streaming sources.

## Feature
Investigate how the mapping conformance rule can be implemented stream-friendly.

- [x] Find a way to transform a mapping table into a local map
- [x] Find a way how to create a run-time-generic UDF depending on mapping table schema
- [x] Implement a broadcasting strategy for the mapping rule for simple data frames.
- [x] Add support for nested structs and arrays

Edit: promoted a couple of items as separate issues (#1129, #1130).

**Comment by yruslan** [comment]
Thinking of rewriting the broadcasted mappings from
```
Map[Seq[Any], Any]
```
to
```
Map[Seq[String], Any]
```
and convert all mapping table key fields to strings. This will help to 
* Remove code duplication for UDFs with a various number of parameters and switch to a UDF that takes an array of string columns. Spark converts all primitive columns to strings in this case automatically, no need even to cast columns.
* (need to confirm) Look up the map if dataset field types do not match exactly. For example, a mapping table with fields `key1: Int, key2: int, value: String` is joined with a dataframe with keys `key1: Long, key2: Long`

The disadvantage of this approach - the mapping table might take more memory.

The decision can be made later once all other features of the broadcasting mapping rule are implemented.

**Comment by GeorgiChochov** [comment]
Any release notes for this?

**Comment by yruslan** [comment]
Not sure. These are all preparation tasks. We can have full release notes on the broadcasting strategy when #1129 is done.

**Comment by GeorgiChochov** [comment]
Alright
