### ISSUE TITLE
Convenience scripts export wrong version of SPARK_HOME 

### ISSUE THREAD

**Issue by HuvarVer** [AbsaOSS/enceladus#1018]
## Describe the bug
In `/scripts/bash/enceladus_env.template.sh` we export `SPARK_HOME` version 2.4.3 instead of 2.4.4

## Expected
Spark 2.4.4

**Comment by Zejnilovic** [comment]
For release notes: Bumped the version of SPARK environment variable from 2.4.3 to 2.4.4
