### ISSUE TITLE
Script to create new version of docs

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1039]
## Background
When transitioning from one version to another, most of the previous one would remain unchanged, except some tiny alterations in each file. That would be nice to automatize.

## Feature
Create a script which copies and alters the files of previous version of documentation to the new version. And also registers the new version to be seen.

**Comment by GeorgiChochov** [comment]
There's a merged PR for this, can we close it?

**Comment by Zejnilovic** [comment]
Yes, thank you for the reminder.
