### ISSUE TITLE
SonarCloud Integration

### ISSUE THREAD

**Issue by hamc17** [AbsaOSS/enceladus#1041]
## Background
SonarQube/SonarCloud integration has been requested for the project

## Feature
Codebase analysis

## Proposed Solution
An update to either the Jenkinsfile to run an additional build step or the addition of a SonarCloud properties file to perform the analysis of the codebase

**Comment by GeorgiChochov** [comment]
## For Release notes
The project now has basic SonarCloud integration fro static code analysis.
