### ISSUE TITLE
Add CODEOWNERS

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#1049]
## Background
Github provides [CODEOWNERS](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) functionality.

## Feature
If we use a `CODEOWNERS` file we can automatically assign reviewers to pull requests.

**Comment by GeorgiChochov** [comment]
Typo in `lokm01` username

**Comment by Zejnilovic** [comment]
Reopened for #1059
