### ISSUE TITLE
Runs view throws 500 if there is too many Run objects do display

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1053]
## Describe the bug
In case there is more than 100MB of Runs object to be queried, Menas will throw a 500 because Mongo has a limit of 100MB for a sort operation.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Have more than 100MB worth of Runs objects
2. Try to display runs
3. See error

## Expected behaviour
Having a lot of Runs should not stop me from viewing them

**Comment by GeorgiChochov** [comment]
## For release notes
To allow `Run Summaries` queries to serve requests with hundreds of thousands of Runs, Menas now allows MongoDB to spill to disk when it reaches the 100MB memory limit for sorting queries.
