### ISSUE TITLE
Materialization of enceladus jars in oozie (quietly) fails when fetching from remote maven repo

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#1069]
It only saves first couple of hundred KBs.

**Comment by GeorgiChochov** [comment]
There is a merged PR for this, but it's still open, can we close it? Could you add release notes for it?

**Comment by lokm01** [comment]
Release notes
Fixed issue with initialization of enceladus jars for oozie integration when fetching binaries from remote maven repo.
