### ISSUE TITLE
Unexpected schema validation error with null in default value.

### ISSUE THREAD

**Issue by HuvarVer** [AbsaOSS/enceladus#1073]
## Describe the bug
In documentation Schema Usage ( #1060 ) there is information about allowing the null value for default key in the metadata. But if there is in schema null value dor defaults the standardization job fails to schema validation. 
'ERROR stages.SchemaChecker$: Validation error for column 'slovo', pattern '': null is not a valid value for field 'slovo'' 

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Have schema with field with a default value equal to null.
2. Have data with field use the default value.
3. Run standardization

## Additional context
I tried it for field types 'string' and 'decimal'. The error message is analogical for both.

**Comment by benedeki** [comment]
Turns out, the problem was, that the field wasn't nullable (`"nullable": false`), then `null` is not an allowed value. Added an explaining comment into documentation.
