### ISSUE TITLE
Broadcast mapping rules should support joining fields on different array levels.

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1078]
## Background
Broadcasting strategy for mapping rules is introduced in #1017 as an implementation of the mapping rule for streaming, and also as a batch job optimization for small mapping tables.

However, the current implementation of helper functions for transformation inside arrays (aka `DeepArrayTransformations`) allows applying transformations only on the same level of nesting. This is because the input argument provided by the lambda function is associated with the struct field inside the deepest array in the path.

But from the perspective of mapping rule, joining on fields on different levels of array nesting makes perfect sense.

Consider the following example
```
   root
   |-- id: long
   |-- countryCode: long
   |-- field1: long
   |-- tradeLeg: array
   |    |-- element: struct
   |    |    |-- operationType: long
   |    |    |-- field2: long
   |    |    |-- field3: string
```
It makes perfect sense to join such a dataframe against a mapping table that has key fields `countryCode` and `operationType`. And it is possible to do using the current explode/collect implementation of the mapping rule.
But, the broadcast strategy for the mapping rule does not support such joins since it requires all join fields to be present at the same level of nesting.

## Feature
We need to add support for looking up a mapping table by keys on a different level of nesting.
This will require adding new tools to `DeepArrayTransformations`

## Proposed solution
A nested transform method such as `nestedStructMap()` can provide a function as a parameter to the lambda function such as `getField()`. Users can pass the full path to that function and it should return a Column for that field.
For root level fields it will return `col(name)`, for array tested fields it will return `vx(name)` where `vx` is the deepest array column in the path.
The usage will be something like:
```scala
val dfOut = nestedStructMap(df, columnPath, "combinedField", getField => {
    concat(getField("countryCode"), getField("tradeLeg.operationType"))
})
```

**Comment by GeorgiChochov** [comment]
Is this done? There is a merged PR associated with it. If it is, does it need release notes?

**Comment by yruslan** [comment]
Yes, missed that. Will add release notes.

**Comment by yruslan** [comment]
Release notes
Improved broadcast strategy for the mapping conformance rule. It can now join fields located at different array levels. This mapping rule strategy is planned to be turned on in experimental mode in Enceladus v. 3.0.0.
