### ISSUE TITLE
User being in too many groups creates too big cookie, browser then rejects it

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1080]
## Describe the bug
When the user has too many groups, the cookie created becomes too big and the browser rejects it.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Have/be in too many groups
2. Try to log in

## Expected behaviour
I should be able to login

**Comment by GeorgiChochov** [comment]
## For release notes
Fixed issue with JWT cookie inflating beyond the cookie size-limit that browsers accept.
