### ISSUE TITLE
Schema version list remains cached when creating entitites

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1084]
## Describe the bug
When creating entities the schema versions in the dropdown is kept cached.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Create one dataset
2. Go and try to create 2nd one

## Expected behaviour
I expect it to be empty or not to behave as empty

## Screenshots
 ![image](https://user-images.githubusercontent.com/17467768/70029516-94e55280-15a7-11ea-8d30-b2ae83a78eb5.png)

**Comment by lokm01** [comment]
This seems fixed?

**Comment by Zejnilovic** [comment]
Re-tested. Seems fine
