### ISSUE TITLE
Add dynamic resource allocation options to run scripts

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1098]
## Background
Currently, run scripts allow specifying only fixed (static) resources for a job.

## Feature
We need to extend run scripts to allow specifying dynamic resource allocation options.

The exact details to be discussed and put here:
```
placeholder
```

**Comment by DzMakatun** [comment]
To enable DRA the following is needed:
 - Enable external spark_shuffle service in YARN (note that it is version specific)
- Set spark.dynamicAllocation.enabled to true
- Add 'spark.shuffle.service.enabled true' to Spark defaults

Parameters for spark-submit:
--conf spark.shuffle.service.enabled=true \
--conf spark.dynamicAllocation.enabled=true \
--conf spark.dynamicAllocation.minExecutors=0 \
--conf spark.dynamicAllocation.maxExecutors=8 \

Note: should be careful with maxExecutors. Spark adds a new executors whenever there are tasks in the queue. Typically one task is created per HDFS partition (with a minimum of 2). E.g. for 90 GB input file 800 tasks will appear in a queue, and if  maxExecutors is not set appropriately (Integer.MAX_VALUE by default), it will take over entire cluster in a matter of few seconds.

additionally DRA uses the following params as a unit of allocation:
--executor-cores 1 \
--executor-memory 1G \
----num-executors 1 \ (initial number of executors in DRA)

Also (investigation ongoing):
--conf spark.files.openCostInBytes=134217728 \ (could help to avoid spanning too many tiny tasks)

**Comment by DzMakatun** [comment]
resolved in #1362

**Comment by DzMakatun** [comment]
Release notes:
[Allows to set Dynamic Resource Allocation as a default for Enceladus jobs. DRA scales resource allocation to the actual size of the job (input size). Compared to fixed allocation, this makes a) small jobs more resource efficient b) large jobs faster. It reduces the effort for resource configuration on per case basis. 

The updated scripts also ensure adaptive execution is enabled together with DRA. Upon shuffle operations, it adjusts the data partitioning to target sizes i.g. HDFS blocks sizes. This improves the efficiency of resource usage and solves the small files issue (when output was split into too many tiny files).

DRA gets auto-disabled, and spark submit falls back to Spark defaults (preserving other custom parameters) when:
- --num-executors is set. We assume, that this parameter is set when user knows how many resources are needed exactly. Remove this parameter, to enable DRA back. 
- Max number of executors is not set. The parameter prevents a job from taking over entire cluster. This parameter is set by script defaults to a safe value, but can be overwritten.

New parameters and default values of the convenience scripts:
--set-dra true : explicitly eneable/disable DRA
--conf-spark-dynamicAllocation-minExecutors 0 : is strongly recommended to be set to 0
--conf-spark-dynamicAllocation-maxExecutors 4: sets max limit on the number of executors. Should never be empty string or infinity on a shared cluster. Can be adjusted based on expected range on input data.  
--conf-spark-dynamicAllocation-executorAllocationRatio 0.5 : how many executors per task are allocated. (1/value = tasks per executor)
--conf-spark-sql-adaptive-shuffle-targetPostShuffleInputSize 134217728 : target post-shuffle partition size.
  ]
