### ISSUE TITLE
View updates even from canceled edit window

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#11]
If a user clicks edit over Basic Info of any of the models (Schemas, Datasets, Mapping tables), changes description, and then clicks cancel, the change still gets shown in the current window. It almost seems as the update went through.

This goes away after window refresh and does not send any call to database or such.

**Comment by Zejnilovic** [comment]
Component Menas

**Comment by GeorgiChochov** [comment]
> Component Menas

Let's use labels for this
