### ISSUE TITLE
I am unable to set a standardization pattern for dates and timestamps in an array.

### ISSUE THREAD

**Issue by HuvarVer** [AbsaOSS/enceladus#1101]
## Describe the bug
If I need to standardize data with dates or timestamps in an array, I have to set a pattern for them, but there is no possibility. 

## Expected behavior
I should be able to set a pattern for dates and timestamps in arrays. Because standardization needs it for these data types.

## Additional context
The pattern in metadata of array doesn't work, the error in a terminal is: `Dates & times represented as array values need specified 'pattern' metadata.`
If the pattern is in the metadata struct or alone in array type struct that `the file isn't a valid Spark StructType JSON schema`. This error is at the uploading of the schema in Menas.

`{
        "name": "timestamps_array",
        "type": {
            "type": "array",
            "elementType": "timestamp",
            "containsNull": true,
            "pattern": "dd/MM/yyyy HH:mm:ss zzz"
            },
        "nullable": true,
        "metadata": {}
    }`
`{
        "name": "timestamps_array",
        "type": {
            "type": "array",
            "elementType": "timestamp",
            "containsNull": true,
            "metadata": {
               "pattern": "dd/MM/yyyy HH:mm:ss zzz"
                 }          
         },
        "nullable": true,
        "metadata": {}
    }`

**Comment by benedeki** [comment]
Release note:
Support of metadata in arrays of simple types. E.g. `pattern` can be specified for array of timestamps.
