### ISSUE TITLE
Custom templates for the release notes generation script

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/enceladus#1113]
The output format of the release note gen script depends on the target destination and the reader audience. At the moment the script only generates MD template snippet intended to be used by Jekyll to generate GH pages. but if I want, say, include the release notes into an email, GitHub release tag description or blog it somewhere I would need  different format and structure of the output.
A customizable release notes template that one could pass as a script parameter would greatly help in those cases.

**Comment by benedeki** [comment]
Moved to its project https://github.com/AbsaOSS/gh-pages-skeleton/issues/7
