### ISSUE TITLE
Upgrade Spring in Menas

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1118]
## Background
We use an ancient version of Spring framework.

## Feature
Upgrade to current version of Spring

**Comment by GeorgiChochov** [comment]
The version of Spring we use is not ancient, we use `Spring Boot 2.0.x`, which runs on `Spring 5.0.x` but we can update to `Spring Boot 2.2.x`.

**Comment by GeorgiChochov** [comment]
Release notes
Update `Spring Boot` to version `2.2.2`.
