### ISSUE TITLE
Enable to reuse names of disabled entities (reenable, undelete)

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1120]
## Describe the bug
Currently, if an entity is disabled/deleted and an attempt is made to create a new entity with the same name, the error message pops up (see the screenshot below).

## To Reproduce
1. Login to Menas.
2. Create an entity (say, a schema).
3. Delete the new entity.
4. Try to create the same entity with the same name as the one that was deleted.

## Expected behaviour
Users should have a way to reuse names of deleted/disabled entities.

## Screenshots
![Screenshot 2020-01-02 at 10 34 25](https://user-images.githubusercontent.com/4082463/71660476-78c20600-2d4b-11ea-9f7b-1260d8bbd6be.png)

## Possible solutions
We need to decide which is the best way to fix this.
* ~~Allow users to re-enable deleted entities in a historical view (see #65).~~
* ~~Show a question dialog box so the user can re-enable an entity when they create an entity with the same name.~~
* Quietly create a new (enabled) version of a disabled entity when a user tries to create an entity with the same name. _(I'm slightly inclined towards this solution)_

**Comment by GeorgiChochov** [comment]
Let's keep #65 as a separate task.
I think the behaviour we want here is to be able to disable specific versions (and eventually to reenable them #65) and allow fresh versions to be created only on top of completely disabled entities.

**Comment by GeorgiChochov** [comment]
Release notes
Disabled entities can now be recreated, as well as viewed by specifying their name in the URL. But they remain unlisted in the navigation menu and search bar.
