### ISSUE TITLE
Confromance and Standardization error codes overlap

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1128]
## Describe the bug
Some Conformance errors have the same code as the Standardization ones.

## To Reproduce
See `za.co.absa.enceladus.utils.error.ErrorMessage`

## Expected behaviour
Perhaps the Conformance errors should have a different high digit, e.g. _E10001_

**Comment by benedeki** [comment]
They are actually not in conflict. But the ranges overlap.
I will add a little optional PR, to hopefully decrease the risk of conflict to minimum.

**Comment by Zejnilovic** [comment]
Non Regexable strinng then, Relase Notes please

**Comment by benedeki** [comment]
> 
> 
> Non Regexable strinng then, Relase Notes please

I am not sure I get the first part. Release Notes not worth in this case,it would only clutter them. No real change, just an extremely simple refactoring.
