### ISSUE TITLE
Evaluate how spark and parquet handle zoned timestamps

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#114]

**Comment by benedeki** [comment]
So after investigation I found the following: Currently the Spark support for `Timestamp` in it's complexity is rather limited and causes trouble in communication with other Apps. It's little better with `parquet` in its meta parameter of _`isAdjustedToUTC`_. More details can be read in this document: https://docs.google.com/document/d/1gNRww9mZJcHvUDCXklzjFEQGpefsuR_akCDfWsdE35Q

To this article the following recent (from Dec 2018) thread lead me to. In the thread it is discussed that Spark should really improve on its Timestamp support and in the document there are suggestion how to approach it.

TLDR Spark has only one timestamp the 'Instant', which i s adjusted based on the desired/local machine time zone.

But until this is implemented in some future Spark version, we need to handle this consistently.
Task needed
* Optional meta timezone for timezone standardization rule
* Each service should have a configuration to set the timezone it's operating upon, defaulting to GMT. During standardization the timestamp is to be normalized in regard of that setting
* Decide how to handle the standardization of timestamp until full Spark support is there
  1. Run on current timestamp - loss of information, potential mess up of dates
  1. AS above, but the original time zone or lack of it stored in metadata; this could be either in info file, or in the name of the column or something other; lightweight version  - column name differentiation of timestamp utc adjusted and not (= without time zone)
  1. Add a string column of the same name with an agreed suffix (e.g. __tmz_). For timestamps without time zone, the column would be either missing or empty
  1. Standardize into a struct
```
    {
      timestamp: Timestamp,
      original_tmz: String
    }
```
* Add support for offset time zone notation in timestamp format

**Comment by benedeki** [comment]
Optional meta timezone for timezone standardization instruction #155
Each service should have a configuration to set the timezone it's operating upon, defaulting to GMT. During standardization the timestamp is to be normalized in regard of that setting #156
Add support for offset time zone notation in timestamp format #157

**Comment by benedeki** [comment]
Result of discussion is this epic: #175
