### ISSUE TITLE
Unused parameter function

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1142]
## Background
An input parameter of a function is not used

## Feature
Parameter `includeDisabled` in `za.co.absa.enceladus.menas.repositories.VersionedMongoRepository.getLatestVersionValue` is not used in any way. Remove for better code.

**Comment by AdrianOlosutean** [comment]
Release notes:
Removed includeDisabled parameter from VersionedMongoRepository.getLatestVersionValue
