### ISSUE TITLE
Tile Runs on homepage doesn't load runs in menu

### ISSUE THREAD

**Issue by HuvarVer** [AbsaOSS/enceladus#1151]
## Describe the bug
After click on the tile Runs on the homepage of Menas, there is an undefined error 404 in dev tools console and a list of runs in the menu didn't load.

## Expected behavior
After clicking on the tile, it should load a list of datasets. The same behavior as after clicking on button Runs in the Navigation menu.

## Screenshots
![Screenshot 2020-01-15 at 10.50.51.png](https://images.zenhubusercontent.com/5dc2bff3be940c0001fed4e1/8247f1ef-e457-4dbd-8d42-8ff3028ea82f)

**Comment by GeorgiChochov** [comment]
Release notes
Fixed issue with `Runs` tile on landing page not loading the `Runs` in the navigation.
