### ISSUE TITLE
Make the group join mapping rule non-experimental

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1157]
## Background
The group join mapping rule implementation became mature enough to make it non-experimental.

## Feature
Make the group join implementation non-experimental. Reserve the notion of experimental to the broadcasting strategy.

**Comment by yruslan** [comment]
After discussing with @GeorgiChochov decided to do this later. In `2.0` the configs will be changed to turn on experimental mapping rule by default. In `3.0` the old implementation will be turned off completely and the broadcasting strategy will be used as the experimental mapping rule.

**Comment by yruslan** [comment]
The semantics of this issue has changed slightly.
Here are the steps of switching to the new implementation of the mapping rule:
1. Make the experimental rule the default option (this issue)
2. Turn on broadcasting strategy by default
3. Remove the old implementation of the mapping rule (in version `3.0`).

**Comment by benedeki** [comment]
Release notes
The group explosion strategy for mapping conformance rules is turned on by default.
