### ISSUE TITLE
Schema registry integration

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1163]
## Background
Streaming sources encode data in `Avro` format. Avro schema definition can be provided as an Avro JSON or as a URL to the schema registry. In order to be able to define datasets for streaming sources in Menas, we need to be able to import Avro schemes from schema registries.

## Feature
Add support for importing schemas from a schema registry in Menas.

**Comment by dk1844** [comment]
Release notes:
Avro schema can be loaded from URL (without auth), too. (Expecting URL from Schema registry)
