### ISSUE TITLE
Add Run search by Spark app_id 

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#1173]
## Background
It is needed to find corresponding Run documents for given Spark History data

## Feature
Add API api/runs/bySparkAppId/{spark_app_id}
which will return Run document where std_application_id OR conform_application_id equals {spark_app_id}

## Proposed Solution [Optional]
Use mongo query
```
.find(
  {$or: [
      {'controlMeasure.metadata.additionalInfo.std_application_id': spark_app_id},
      {'controlMeasure.metadata.additionalInfo.conform_application_id': spark_app_id}
      ]
  }
)
```

**Comment by GeorgiChochov** [comment]
@DzMakatun I think this is done, right? Could you mark it as part of release 2.1.0, add some release notes here and close it?

**Comment by DzMakatun** [comment]
Release Notes
Add run search by Spark application id via API /runs/bySparkAppId/{spark_app_id}
