### ISSUE TITLE
Push control metrics to a Kafka topic on every checkpoint

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1180]
## Background
Users want to have a pub/sub way of getting realtime data about Standardization and Conformance jobs so they won't need to poll runs using the API.

## Feature
- [ ] Define Avro schema for control metrics to be pushed to Kafka.
- [ ] Add an Atum plugin to push metrics to Kafka.
- [ ] Make it configurable (on/off switch, Kafka endpoints, topic name, etc) in `application.conf`.
- [ ] Make sure control metrics are pushed on each checkpoint.

## Proposed Solution
- The Menas plugin for Atum can be used as a reference implementation (see `za.co.absa.enceladus.dao.menasplugin`).
- Check if the prior work on that in `za.co.absa.enceladus.external.kafka` can be used.

**Comment by yruslan** [comment]
This issue is moved as a separate project owned by @TarannumPraveen 

https://github.com/AbsaOSS/enceladus-plugin-kafka

Maybe we can close this.

**Comment by benedeki** [comment]
I can imagine some really big lugins would have their own repo (ATUM for example). But what about smaller ones?
For the record, I don't know if this particularly would be a "big" or "small" plugin. 😉

**Comment by yruslan** [comment]
The Kafka plugin might not be big, but it is owned by a different team so a separate repository for this plugin seems a good idea.

**Comment by benedeki** [comment]
Yup, makes sense. Closing the issue here.
