### ISSUE TITLE
Audit all REST API request/responses

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1181]
## Background
This is just an idea for a quick discussion. 

In order to understand how Enceladus API is used, we might want to have an audit of all REST requests, response codes and error messages to be stored somewhere for later analysis, maybe in a MongoDB table?

## Feature
Save all request URLs/response codes/error messages with user names and timestamp into a collection in our database (rest_audit?). It can help us to see who did what in case we need it. No need to store response bodies, of course.

**Comment by Zejnilovic** [comment]
Maybe do it after the general clean up? (#965) Otherwise, it sounds good.

**Comment by yruslan** [comment]
Yeah, agree. Also, @GeorgiChochov suggested the better way to do this is to use Logstash and ElasticSearch.
