### ISSUE TITLE
The wrong datatype instead of array breaks standardization for the whole row.

### ISSUE THREAD

**Issue by HuvarVer** [AbsaOSS/enceladus#1187]
## Describe the bug
Incorrect std process for whole row when there is a different data type in raw data instead of the defined array in a schema.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Have schema with defined array (not depends on datatype in the array)
`{
        "name":"array_of_booleans",
        "type":{
            "type":"array",
            "elementType":"boolean",
            "containsNull":false
            },
        "nullable":false,
        "metadata":{}
    }`
2. Have raw data where is e.g. string instead of the array
`"array_of_booleans": "true"`
3. Run standardization (I use 2.1.0)
4. See error in errCol for each record in the row with this data:
`stdNullError, E00002, Standardization Error - Null detected in non-nullable attribute, att_name, [null], []`

## Additional context
[Array_problem.zip](https://github.com/AbsaOSS/enceladus/files/4219638/Array_problem.zip)
See the raw with first column `"property": "wrong_type"`

**Comment by benedeki** [comment]
Release notes:
If input data does not adhere to schema (complex type to primitive type) it's detected and either new error type is added to `errCol` of the defective row (default) or processing stopped with exception altogether (in case a new switch `--strict-schema-check` is set to `true`)
Parquet, and and any other future format without enforced schema, now behaves similarly as XML or others on a missing column - it's considered NULL
