### ISSUE TITLE
Unit tests fail on Windows

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1210]
## Describe the bug
12 unit tests fail on Windows. Failing unit tests are related to the broadcasting mapping rule and most likely due to line ending (`CR LF` vs `LF`).

## To Reproduce
Run `mvn clean test` on a Windows computer.

## Expected behaviour
All unit tests should pass on any supported platform.

**Comment by benedeki** [comment]
It works for me without issues. My Git setup is `core.autocrlf input` See https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

We could make the tests CRLF/LF agnostic by introducing normalization before assert. But do we want to? 🤔
