### ISSUE TITLE
Check Spark version compatibility at startup

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1222]
## Background
Currently, Standardization and Conformance will fail with unobvious error messages if an incompatible version of Spark is used.

## Feature
We can check Spark version at startup and fail immediately with a proper error message if the version is not compatible with the job.

**Comment by yruslan** [comment]
Forgot to add. The code for Spark version checking might be reused in other projects, such as Hyperdrive (@jozefbakus , @kevinwallimann).

**Comment by dk1844** [comment]
Release notes
 - Spark version checking (currently >=2.4.2, <3.0.0) for Conformance and Standardization
