### ISSUE TITLE
Extract most/all logic from DynamicConformanceJob

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1232]
## Background
`DynamicConformanceJob` contains the `main` function but also a lot of surrounding processing that is hard to test

## Feature
Move the application logic in `DynamicConformanceJob` into dedicated classes, for easier testing and to share common code with **Standardization**.

**Comment by AdrianOlosutean** [comment]
[Release notes](https://github.com/AbsaOSS/enceladus/issues/1015#issuecomment-658688854)
