### ISSUE TITLE
Check if STD path exists before running conformance

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1239]
## Background
Currently, if standardization folder does not exist during conformance, the error is NoFileFound and a message that metrics failed.

## Feature
Before anything from conformance, check if standardization folder exists and if not, throw an error.

## Proposed Solution [Optional]
```scala
if (!fsUtils.hdfsExists(pathCfg.stdPath)) {
      throw new IllegalStateException(
        s"Path ${pathCfg.stdPath} does not exist. Conformance has no input data")
    }
```

**Comment by AdrianOlosutean** [comment]
Shouldn't the same apply for raw path too in the Standardization case?

**Comment by Zejnilovic** [comment]
> Shouldn't the same apply for raw path too in the Standardization case?

Sorry @AdrianOlosutean missed this one. Yes, sounds good.

**Comment by AdrianOlosutean** [comment]
Release notes
Input paths for each job gets validated
