### ISSUE TITLE
Add Adrian to the codeowners

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1258]
## Background
When a user is a code owner, they are added automatically to the list of reviewers. In our team all devs are reviewers by default.

## Feature
Add Adrian to the code owners.

## Proposed Solution [Optional]
Add `@AdrianOlosutean` to `.github/CODEOWNERS`

**Comment by benedeki** [comment]
Also do for `gh-pages` branch.

**Comment by AdrianOlosutean** [comment]
Merged into develop and gh-pages

**Comment by AdrianOlosutean** [comment]
Release notes:
Added Adrian to CODEOWNERS in develop and gh-pages
