### ISSUE TITLE
Make sure 'Source' and 'Raw' checkpoints are present when Standardization starts

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1285]
## Background
We need to start more strict validations of incoming _INFO files.

## Feature
Make sure 'Source' and 'Raw' checkpoints are present when Standardization starts.

## Additional context
It might require changes to Atum to allow clients access to checkpoints (instance of `ControlMeasure`)

This is related to #1186

**Comment by AdrianOlosutean** [comment]
Release notes:
Validate source and raw checkpoints are present in Standardization
