### ISSUE TITLE
Reverse ordering of versions in version pickers

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1290]
## Background
When people need to select a version current order is ascending. But usually, most used versions are the latest ones

## Feature
Reverse ordering of versions from ascending to descending.
Version pickers are: 

- Schema version when Creating/Editing dataset
- Schema version when Creating/Editing mapping table
- Adding/editing a mapping conformance rule

**Comment by lokm01** [comment]
Release notes
Menas - Reverse ordering of entity versions in version pickers
