### ISSUE TITLE
Add 'enceladus_record_id' during processing

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1294]
## Background
We need a unique record identifier so that errors sent to a DQ topic can be traced back to the original record.

Various data sources might have very complicated primary keys, some might not have primary keys. 

## Feature
We should generate our own 'enceladus_record_id' based on GUUID, for instance.

This should be done in Standardization and Conformance similarly to how we generate 'enceladus_info_date' and 'enceladus_info_version'. Conformance should generate these filelds only if they are absent.

**Note** Usage of GUUIDs is a straightforward solution. If you have better ideas - please let us know, let's discuss.

**Comment by Zejnilovic** [comment]
Thinking about testability. Could we generate GUUID so it is "always same"? My idea is if we run standardization twice, can we compare the datasets? It could also help us with "merging" the data and figuring out what changed between report versions.

**Comment by dk1844** [comment]
I am thinking if we based this ID generation on a random generator, one could provide a seed - so, if the tests always provided the same seed, the ID generation could be always the same.

We could use the default seed for production then. What do you think, @Zejnilovic?

**Comment by Zejnilovic** [comment]
A seed sounds like an interesting idea. If I then run standardization twice, would it generate the same IDs?

**Comment by dk1844** [comment]
I think it should, but have not coded it yet, just thinking. If we agree this is the way to go, I can jump on it.

Based on some [ideas presented here](https://stackoverflow.com/a/49736088/1773349), I could use the `org.apache.spark.sql.functions.rand()` with or without seed. I could expose the ability to provide the seed via a method or a parameter and then use the result of the rand to `java.util.UUID.nameUUIDFromBytes`.

This way, we could, I hope, get a reproducible random set of record ids.

tagging @benedeki as he wanted to be part of the discussion.

**Comment by yruslan** [comment]
UUID generation routines guarantee that generated values are globally unique. We can use this property in prod.

For testing, we can replace the generator with the one that uses a fixed seed.
I'd limit the usage of `rand()` with `java.util.UUID.nameUUIDFromBytes` for unit test only since we need to make sure generated ids are unique in prod. And `rand()` doesn't provide such guarantees.

Alternatively, tests can just drop the id column before doing comparisons.

Anyway, there is another issue potentially. If the same data is conformed using batch and streaming jobs, we can't match unique ids since they are generated independently. But this is just a hypothetical issue, so let's not to focus on it for now.

**Comment by Zejnilovic** [comment]
> For testing, we can replace the generator with the one that uses a fixed seed.

Hermes will have an option of supplying schema later on. But Unit Test I think will need something "static"

> Anyway, there is another issue potentially. If the same data is conformed using batch and streaming jobs, we can't match unique ids since they are generated independently. But this is just a hypothetical issue, so let's not to focus on it for now.

This is what I meant when saying "merging" the data

**Comment by dk1844** [comment]
Thinking about the testing -- do you need the testing repeatable uuids implementation to be available from the outside of the module overridable via a spark property or similar? Or just for internal tests of the module itself? @Zejnilovic

**Comment by Zejnilovic** [comment]
It would be nice if we could add some -D java option to use "simple generation". But if it is too hard. Just scrape it, and I will add a feature to Hermes to ignore it.

**Comment by benedeki** [comment]
What if the data have a native key? I understand that the "no" strategy will save us the work, doesn't meat though, the key is known.

**Comment by dk1844** [comment]
> What if the data have a native key? I understand that the "no" strategy will save us the work, doesn't mean though, the key is known.

The idea is that one can submit the job with `-Denceladus.recordid.generation.strategy=no` and no other key-column will be added.

Is there a case that these options (`true`, `pseudo`, `no`) are not sufficient for, @benedeki?

**Comment by dk1844** [comment]
Release notes:
"enceladus_record_id" column is added in Enceladus (Standardization/Conformance) if it does not exist. By default it contains UUID for each record, but the implementation is overridable with `-Denceladus.recordId.generation.strategy={uuid|stableHashId|none}`

**Comment by dk1844** [comment]
Unclosed because of the documentation PR https://github.com/AbsaOSS/enceladus/pull/1327.
