### ISSUE TITLE
Upload schema from a secure schema registry

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1299]
## Background
This is requested by our users as something that would be very helpful to them.

## Feature
Upload schema from a secure schema registry.

@kevinwallimann gave a great idea how we can simplify all these things.

We should add support for specifying the subject of a schema registry.
The base URL of schema server should be configured in Menas in `application.properties`

User should provide:
- [x] A subject in the schema registry. ~For the naming strategy based on the topic name it will be `topic_name`-`value`.~
- ~[ ] An optional key subject might be specified (e.g. `topic_name`-`key`). If it is specified, the schema of the key should be merged with the value schema.~
- [x] if the provided `topic_name` does not exist,  there should be an automatic (behind the scenes) fallback to `topic_name-value`. If even that does not succeed, the schema loading fails.
 
Menas should:
* Upload the schema from the schema registry.

**Comment by dk1844** [comment]
Release notes
Schema can be updated by specifying schema-name (-value will be appended, optionally also -key). Secure schema registry is supported, too.
