### ISSUE TITLE
Add an end-to-end Kafka source&sink streaming conformance integration test

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1307]
## Background
An end-to-end streaming conformance test will help to catch streaming-only issues.
Such as the Catalyst optimizer issue #1306  

## Feature
Add an end-to-end Kafka source&sink streaming conformance integration test.

* Data for the test can be usual JSONs. We can even reuse the existing end-to-end conformance test data for that.
* An instance of Kafka should be brought up.
* Data from the examples should be sent to raw Kafka topic converting the input data to Avro.
* A streaming conformance test should be run as Kafka -> Parquet and Kadka -> Kafka

## Proposed Solution [Optional]
Use https://www.testcontainers.org/modules/kafka/
It is used by Hyperdrive as well. Thanks Felipe for the suggestion.

**Comment by yruslan** [comment]
There is one additional thing unit/integration tests of streaming conformance should check. It is the way `enceladus_info_date` and `enceladus_info_date_string` are created. It should support a constant value, processing time, and event time column. The strategy for generating these columns are determined by command line parameters.

**Comment by AdrianOlosutean** [comment]
Release notes
Created Integration test for HyperConformance which checks `enceladus_info_date` for constant and event_time
