### ISSUE TITLE
Add attempt id to runs

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#1309]
## Background
When a Spark job is submitted to YARN in cluster mode it may have multiple attempts. Attempts have the same app_id and different attemptId. (see [Spark History API docs] https://spark.apache.org/docs/latest/monitoring.html#rest-api)
As a result, in Menas, the later attempts will create new runs for std OR rewrite run data for conformance.
Currently Menas logs std_application_id and conform_application_id.
For monitoring, it is important to know the attempt id as well.

## Feature
Store Spark attempt id to Run documents in Menas.

## Proposed Solution 
Solution Ideas 

1. Check if attempt id exists and append it to metadata using Atum

**Comment by AdrianOlosutean** [comment]
If I understood correctly, there should be multiple runs stored with different attempt_ids. In this case it seems like there should be a composite key for run objects. Is this option OK or should there be some other approach?

**Comment by yruslan** [comment]
Actually, I'm not sure how attempts are handled in Menas. Looking at the way it is currently implemented it overwrites the run object with the last attempt. I think this makes sense. Failed attempts do not leave traces in data and probably we should not track failed attempts if they are followed by a successful one.

I think what we should do is just append `std_spark_attempt_id` at the end of Standardization and `conf_spark_attempt_id` at the end of Conformance to additional properties in Atum's metadata.

**Comment by AdrianOlosutean** [comment]
Release notes:
Spark attempt_id added as additional info in _INFO file
