### ISSUE TITLE
_INFO file checkpoints validation should be more verbose on error

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1317]
## Background
_INFO file checkpoints validation should be more verbose on error. Now it is just `Checkpoint validation failed`

## Feature
When checkpoint validation fails tell user something like: "_INFO file's validation failed. Mandatory field XY was not found in checkpoints"

**Comment by AdrianOlosutean** [comment]
Release notes:
Verbose _INFO file checkpoints validation
