### ISSUE TITLE
Update Release Notes of 2.4.0

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1318]
## Background
Release notes 2.4.0 don't speak in full about _INFO files now mandatory fields. This changes seems rather big (usability wise) and is not explained well enough for outside users.

From
`#1285 Validate source and raw checkpoints are present in Standardisation`
to
`#1285 Standardisation now validates _INFO file's checkpoints. Checkpoints Source and Raw are mandatory. Field names are case insensitive.`

**Comment by benedeki** [comment]
I think it might be worth it to make a decent documentation on _INFO file requirements, Thus users would know how to fix existing ones and not block the release of 2.4.0.

**Comment by Zejnilovic** [comment]
> I think it might be worth it to make a decent documentation on _INFO file requirements, Thus users would know how to fix existing ones and not block the release of 2.4.0.

That is for the Usage part of the documentation (#622). I just want to say a bit more in the Release Notes (enhance them) by this Issue. We agreed that every PR must have an Issue tied to it, The release is not blocked.

**Comment by benedeki** [comment]
Well, is this enough for teams to fix their _INFO files? If yes, than indeed it's would "unblock" the deployement of 2.4.0 release :-)
Maybe @zakera786 could confirm this is good enough. 🤔

**Comment by benedeki** [comment]
Clarified in F2F discussion with @Zejnilovic . This is good for now.
