### ISSUE TITLE
Add support for specifying CSV characters as codes

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1319]
## Background
When Standardization is ran from a scripting environment sometimes recodes characters depending on the current encoding. This causes failures of jobs that use higher ASCII characters as delimiters, for instance.

## Feature
Add the ability to specify delimiter, quote and escape character as a UNICODE expression instead of the character itself.

From UNICODE table: https://en.wikipedia.org/wiki/List_of_Unicode_characters

## Example [Optional]
So that you can specify the character like this:
`--delimiter U+00A1` or `--delimiter u00a1` or `--delimiter 0161`
instead of this
`--delimiter ¡`
(`--delimiter ¡` should still be supported)

Same for `--escape` and `--quote`.

## Proposed Solution [Optional]
Check format of the option and decode it into the UNICODE `String` (changed from `Char` since an empty string is allowed).

We can have a character interpreter utility function that converts a command-line character argument to the actual character or an empty string.

**Comment by yruslan** [comment]
@Zejnilovic pointed out that quote and escape characters can be turned off by passing an empty string. But passing `--csv-quote ""'` does not pass an empty string, it tries to use double double quotes as a quote character.

Let's add a special value denoting an empty string, e.g. `--csv-quote no` or `--csv-quote off`.

**Comment by benedeki** [comment]
I would implement a special switch `--no-csv-quote`. The keyword looks arbitrary and the double quotes is harder to enter.

**Comment by AdrianOlosutean** [comment]
I tend to think that adding a new switch would be redundant. How about having text values like: `none`, `double` and `single` ?

**Comment by yruslan** [comment]
The good thing about having a single switch is that we can utilize the logic for other types of characters, e.g. 'escape' and [in the future] comment. Otherwise, we will need to add `--csv-no-escape` 😆 and `--csv-no-comment` 😄

**Comment by yruslan** [comment]
I like both ideas and open to opinions, just slightly inclined towards the single command line parameter.

**Comment by benedeki** [comment]
The multiplication of switches is a good point.
But having a custom keyword is not very intuitive - would still have to be documented and emphasized so people notice the special case. furthermore there's a chance of conflict (very low, I am aware, but the world is big).
If we are going with one switch I would support the double quotes and double double quotes (and again described in the documentation)

**Comment by yruslan** [comment]
> If we are going with one switch I would support the double quotes and double double quotes (and again described in the documentation)

`--csv-quote ''` and `--csv-quote ""` already works. We just want to support other ways as well since when running from bash scripts calling other bash scripts quotes could disappear.

**Comment by benedeki** [comment]
I would then just describe it in documentation.
And if the worry is of the disappearance an idea:
- dedicated switch `--no-csv-quote` while implementing a smart handing of `no` prefix on switches, so we don't need to bother implementing it repeatedly. 🤔

**Comment by Zejnilovic** [comment]
Can I have a bit of a non traditional suggestion on the approach. 

Get rid of scopt. Create your own parser. And everything that is extra (everything format related) goes as a map into DataFrameReades's options method. [Hermes](https://github.com/AbsaOSS/hermes/blob/develop/datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/cliUtils/DataframeOptions.scala) does that and in doing so basically allows any format that follows the rules of spark readers. I then don't have to think of every possible options that a read can have. And Spark has quite good error messages in case someone passes bad options.

**Comment by yruslan** [comment]
It's a good idea, @Zejnilovic . Spline has a very nice Scala-friendly command-line parsing tools we can steal. But let's do it as a separate task.

@benedeki , Yeah, this might be the best approach. Both `--csv--no-quote` and `no` as a special value. 

And the most important thing - allow codes instead of actual symbols. Since symbols from higher ASCII (like `¿`) get corrupted when bash scripts run in different charsets.

**Comment by AdrianOlosutean** [comment]
Release notes:
Csv parameters(delimiter, quote and escape) can be specified as unicode such as: `U+00A1`, `u00a1` or `0161`. Additionally, for specifying `""`(empty string), meaning for example no escape, no quote, the value `none` was added.
