### ISSUE TITLE
Information date column support for streaming jobs

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1333]
## Background
Streaming data may contain an event date or timestamp. We should use it if it is available to populate 'enceladus_info_date'.

## Feature
Add a configuration option to specify a column name to be used to derive `enceladus_info_date` from. It can be `date` or `timestamp` or `string`. If it is a string, users need to be able to specify a pattern for that field.

**Comment by benedeki** [comment]
Does this feature make sense for batch mode as well?

**Comment by Zejnilovic** [comment]
> Does this feature make sense for batch mode as well?

In the current architecture report date is precisely this, is it not?

**Comment by yruslan** [comment]
Here is my current understanding. In batch mode information date is
* For snapshot-type data: the EOD date when a snapshot of the database was created
* For event-based data: event date [presumably].

in both cases the information date is supplied to as
* in a field of the _INFO file
* as the command line parameter

We have a requirement that we should validate that these 2 information_date sources point to the same date.

**Comment by yruslan** [comment]
Release notes
Added an ability to specify information date source for streaming conformance jobs. It can be either an event time column, processing time, or a constant value.
