### ISSUE TITLE
Use reference.conf instead of application.conf

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1344]
## Background
This is originally pointed out by @Zejnilovic. Since we use Typesafe config the better way of supporting base configuration is to use `reference.conf` instead of `application.conf`.
More on that: https://github.com/lightbend/config#note-about-resolving-substitutions-in-referenceconf-and-applicationconf 

Related: #510 

## Feature
- [ ] Rename `application.conf.temptale` to `reference.conf` in all modules that use TypeSafe config (`menas`, `spark-jobs` and `utils`).
- [ ] Remove the ant POM plugin that did the copying from `application.conf.template` to `application.conf`

**Comment by dk1844** [comment]
In regard to what I warned about in https://github.com/AbsaOSS/enceladus/pull/1330#discussion_r425023705, I then suggest that it may be beneficial to log out the resulting config in order to be able to clearly see what the outcome of `reference.conf+application.conf` actually was (mostly to be able to quickly asses successful overriding). I have seen this being quite helpful more than once. 😉

**Comment by Zejnilovic** [comment]
I know I sound like a broken record on this one, but how about that config object with validations? 

Logging of the configuration is good as well. But to "hide" what user might not want to show, we could load reference.conf, exclude application.conf keys from it and print only defaults used. This way no sensitive data would be shown.

**Comment by dk1844** [comment]
If "config object with validations" means what I think it means, I welcome it. (Please elaborate?)


Regarding the sensitive data: A solution I have seen is that certain config keys are marked as sensitive and they are redacted prior to the logging - that way, everything is printed except for the sensitive data. This is convenient in being oblivious to any changes in non-sensitive fields.

---
You don't sound like a broken record (if anyone it would be me with the reference.conf bashing), it's clear that we both just want the possible downsides of each approach to be taken into account.

**Comment by Zejnilovic** [comment]
> If "config object with validations" means what I think it means, I welcome it. (Please elaborate?)

There is this config abstract class in Hermes, which is then implemented by one TypeSafe config class and one "manual" config class. And this object is aware of all the configs, on initialization, it validates the values, and it is being passed where needed. 

I have a manual class there for the people who would like to use Hermes as a library.

Please visit Hermes [config folder](https://github.com/AbsaOSS/hermes/tree/develop/datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/config)

**Comment by yruslan** [comment]
I like the idea of printing the effective config along with sensitive values redacted. We can redact all known sensitive fields and fields that contain 'password' in the key.

I remember the implementation of several types of configs in Hermes. Not sure we need it here. TypeSafe config can be generated on the fly for tests without the need for an additional class hierarchy. But we can discuss this. Also, I remember Spline has a very cool concept working with configuration. But I'm also not sure if we need it here. Spline has several config sources such as built-in application.conf, hadoop config, spark config, system properties. Our use case is much simpler.

**Comment by yruslan** [comment]
Converting this to Epic since different and independent changes need to be made in
- Menas,
- spark-jobs
- migrarions
