### ISSUE TITLE
Menas attachment versioning is off by one

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/enceladus#1347]
## Describe the bug
A schema version in Menas and the internal Menas attachment version is off by one (e.g. for schema version 2, the attachment version is 3)

## To Reproduce

1. Create a new schema. Its version will be "1".
2. Upload/Load schema file for it, version of the schema will be "2".
3. Attempting to export the schema file using "Export File" will fail, because Menas will look for attachment v2, but only attachment v3 would exist. 
4. Moreover, if you upload another version of the file and attempt to "Export File", you will get the older file instead of the latest uploaded.

## Expected behaviour
 - everytime there is a schema file attached (v2+), the UI should allow to "Export File" and get the correct result (e.g. the latest file that was just uploaded)

## Additional context
This could most probably be fixed by changing:
```scala
refVersion = version + 1
```
to 
```scala
refVersion = version
```
in `SchemaController.scala`.

However, this can also lead to unmatched expectations with our users (they may have exported schemas they thought were the lastest, but weren't and so on).

**Comment by Zejnilovic** [comment]
This issue comes from version 1.2.2. Things before are fine.

**Comment by dk1844** [comment]
Release notes
Each time schema gets updated by uploading/remote-loading a new schema-file, the attachment is filed under the same version. (There may be holes in the attachment version because schema could be updated without changing the attachment - e.g. when its description changes)

**Comment by dk1844** [comment]
This is another version of the bug-fixing mapping script, feel free to take it for a spin (@Zejnilovic et al.)
```javascript
// This script attempts to find corresponding documents in schema_v1 and attachment_v1 collections by
// s.name == a.refName && "datetime from _id being about the same" (about: abs(ts1-ts2) <= epsilon)
var epsilon = 200; // in millis, 

db.getCollection('attachment_v1').aggregate([
   {
     $lookup:
       {
         from: "schema_v1",
         let: { rname: "$refName", rid: "$_id", upperBound: {$add: [{"$toDate":"$_id"}, epsilon/2]}, lowerBound: {$subtract: [{"$toDate":"$_id"}, epsilon/2]} },
         pipeline: [
              { $match:
                 { $expr:
                    { $and:
                       [
                         { $eq: [ "$name",  "$$rname" ] },
                         { $lte: [{"$toDate":"$_id"}, "$$upperBound"  ] },
                         { $gte: [{"$toDate":"$_id"}, "$$lowerBound"  ] }
                         
                       ]
                    }
                 }
              }
          ],
         as: "schemaInfo"
       }
  },
  { $project : { refName: 1, refCollection : 1, refVersion: 1, "schemaInfo.name": 1, "schemaInfo.version": 1, "schemaInfo._id" : 1} }, // root _id is included by default
  { $out : "remapping_evidence1347"} // saves data as collection - relation with issue #1347
])
  
var bulkOps = db.remapping_evidence1347.find().map(function (doc) { 
    
    if(doc.schemaInfo.length != 1) {
        print(`Match for ${doc._id} inconclusive (found ${doc.schemaInfo.length} matches), omitted from remapping!`);
        return;
    }
    
    var schemaData = doc.schemaInfo[0];
    var schemaVersion = schemaData.version;
    var attachmentVersion = doc.refVersion;
    
    //debug:
    //print(`Match for ${doc.refName}: schema version ${schemaVersion}, attachment version ${attachmentVersion}`)
    
    if (schemaVersion < attachmentVersion) { // attachment v can be lower if schema was edited (without new attachment being added)
        
        print(`Attachment ${doc._id} for ${doc.refName}: schema v. ${schemaVersion}, attachment v. ${attachmentVersion} -> ${attachmentVersion-1}`)
        // remap attachment version
        return { 
            "updateMany": { 
                "filter": { "_id": doc._id } ,              
                "update": { "$inc": { "refVersion": NumberInt(-1) } } 
            }         
        };
    }
    
});

// bulkOps contain undefined for ops that did not satisfy the "schemaVersion < attachmentVersion" condition
var bulkOpsCleaned = bulkOps.filter(function(d) { return d != undefined})

db.getCollection('attachment_v1').bulkWrite(bulkOpsCleaned);
db.remapping_evidence1347.drop() // evidence collection cleanup - comment if you want to keep the record of what was done.
```

**Comment by Zejnilovic** [comment]
> This is another version of the bug-fixing mapping script, feel free to take it for a spin or nitpick 😆 (@Zejnilovic, @yruslan @HuvarVer et al.)

I would never nitpick. BTW works as expected repaired my test DBs

**Comment by dk1844** [comment]
> This is another version of the bug-fixing mapping script, feel free to take it for a spin or nitpick 😆 (@Zejnilovic, @yruslan @HuvarVer et al.)
> 
> ```js
> // This script attempts to find corresponding documents in schema_v1 and attachment_v1 collections by
> // s.name == a.refName && "datetime from _id being about the same" (about: abs(ts1-ts2) <= epsilon)
> var epsilon = 200; // in millis, 
> ...
> ```
FYI: To become part of the codebase in https://github.com/AbsaOSS/enceladus/pull/1355.

**Comment by dk1844** [comment]
Release notes
MongoDb remapping script added to `scripts/mongo/1347-attachment-version-off-by-one-mapping-script.js`.
