### ISSUE TITLE
Sending errors to Kafka should work with Secure Kafka cluster

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1352]
## Background
Since our jobs are supposed to be running on corp environments we expect secure Kafka can be used there,

## Feature
Add support for secure Kafka (Kerberos) and Schema registry (PKI) for the plugin that sends all standardization and conformance errors to Kafka.

## Proposed Solution [Optional]
Jobs are already configured with keystore and truststore paths, as well as jaas.conf. The driver already initializes secure Kafka. Probably need to make sure secure Kafka executors initialize secure Kafka as well. And need to add 
```
kafka.security.protocol="SASL_SSL"
kafka.sasl.mechanism="GSSAPI"
```
if configured in `application.conf`

**Comment by dk1844** [comment]
Release notes
Error messages publishing now works with SSL-secured Kafka topics. Refer to the [`spark-jobs`' `reference.conf`](https://github.com/AbsaOSS/enceladus/blob/develop/spark-jobs/src/main/resources/reference.conf) on how to set it up.
