### ISSUE TITLE
Map support for SparkStruct

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/enceladus#1357]
## Background
We are able to upload AVSC files to Menas now, in case they contain a map type, e.g.
```json
    {
      "name": "stringMapField",
      "type": {
        "type": "map",
        "values": "string"
      }
    }
```
Menas has trouble converting it to Spark Struct.

## Feature
Support AVSC files that contain maps, too.

## Example
 1 Take a testing file [containsMap.avsc](https://github.com/AbsaOSS/enceladus/files/4676291/containsMap.avsc.txt) and upload it to menas. Menas will correctly show the map type: ![map-in-menas](https://user-images.githubusercontent.com/4457378/82798362-b9e0c100-9e78-11ea-8873-320b6b17010f.png)

2 Try to _Export Spark Struct_. This will fail with the following error in the Catalina log:
```
StructType serializer: Failed to convert the JSON string '{"name":"example1","type":"record","namespace":"za.co.absa.example","fields":[{"nam
e":"stringField","type":"string"},{"name":"nullableField","type":["null","string"],"default":null},{"name":"timeStampLikeLongField","type":"l
ong","logicalType":"timestamp-millis"},{"name":"stringMapField","type":{"type":"map","values":"string"}}]}' to a data type.
```

(Note that just exporting the file (as original) works because there is no parsing involved, just the saved Menas attachment is returned)
(Evidence that the map is at fault: omitting the map-type-field from the example file results in _Export Spark Struct_ to be working fine)

## Proposed Solution
Solution Ideas 
1. Implement the map type support alongside the already existing struct-type as another non-trivial type (there could be some similarities)

**Comment by Zejnilovic** [comment]
We already have an issue like this #1198

**Comment by benedeki** [comment]
Closing as duplicate #1198 😉
