### ISSUE TITLE
Standardisation issue parsing numeric dates in JSON data format

### ISSUE THREAD

**Issue by dwfchu** [AbsaOSS/enceladus#136]
Problem:
Standardisation is not casting dates correctly for JSON data formats when value supplied is a numeric

Reproduce problem:

Data:
```json
{
   "MODIFIEDDATE":20190101.235959
}
```
Schema Supplied:

```json
{
      "name": "MODIFIEDTIMESTAMP",
      "type": "timestamp",
      "nullable": true,
      "metadata": {
        "description": "Timestamp when the latest credit analyst to client link was changed.",
        "pattern": "yyyyMMddHHmmss"
      }
}
```
Expected Behaviour:
Standardised value in parquet to:
`2019/01/01 25:59:59` (Timestamp type)

Current Behaviour:
Standardisation fails, default datetime is inserted and error logged in `errCol`

Enceladus version: 
0.4.181

**Comment by benedeki** [comment]
Verification, namely NAN check should be improved as well.

**Comment by benedeki** [comment]
Wasn't able to reproduce.
The example, the way how it is written have two bugs in data. Schema references other field that the one in example data. And also the pattern is wrong - missing the decimal point.
Once both these issues were fixed, the standardization went as expected, timestamp `2019-01-01 23:59:59` gathered.
