### ISSUE TITLE
Comparison Job add mismatch column

### ISSUE THREAD

**Issue by anitadsalves** [AbsaOSS/enceladus#137]
The current testing tool compares two data sets with the same schema, and writes out two files if the two input files aren't exactly the same. 
The files written are : actual_minus_expected and expected_minus_actual. 
The output files contain only the records that did not match but does not indicate which attributes in those records could be the problem.
One then needs to go and inspect the output files manually and look through the records so see which attribute is actually different between the files. 
This can be tedious especially for datasets with many columns and many mismatched records. 

It would be very useful if the testing tool could be re-run over the output files whereby the new output files would indicate exactly which attributes are not matching and it will be easier to see exactly where the mismatches are.

**Comment by GeorgiChochov** [comment]
This seems like the logical next step in building out the `ComparisonJob` tool. I would suggest the following:
* This can only really work where we know some sort of unique identifier for the dataset (#125 sets this up)
* We join the two output datasets based on this unique identifier, which gives us the respective expected and actual record pairs. 
* We can then compare the columns per record
* Mismatching columns can be stored in a new `errors` column in an array of error records: `column: "a", expected: "asd", actual: "dsa"`
* The user can just select on the errors column of the resulting dataset and see all mismatching records.
* The output of the `ComparisonJob` can then log statistics about the contents of the error column before it exits (e.g. total number of errors, number of errors per column, number of missing records on each side - expected but missing and actual but missing) 

@Zejnilovic, how does this sound to you? Wan to bump it as your next?

**Comment by GeorgiChochov** [comment]
This implementation for flat comparisons is sufficient for now. The implementation of nested/deep comparisons would require a much more complex solution, which we don't really need at this time. Let's revisit it at a later point #148
