### ISSUE TITLE
New `main` function combining Standardization and Confromance

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1371]
## Background
Being able to run **Standardization** and **Conformance** in succession with only one initialization would improve the efficiency of the whole process.

## Feature
Create a new `object` with `main` function that will run **Standardization** and **Conformance** logic in one call, combining the logic,

## Proposed Solution [Optional]
Solution Ideas 
1. Leverage the classes/traits from #1015, #1231 and #1232

**Comment by AdrianOlosutean** [comment]
Should this combined job be writing the standardization results as an intermediate step or not? Or should it should be configurable?

**Comment by benedeki** [comment]
> 
> 
> Should this combined job be writing the standardization results as an intermediate step or not? Or should it should be configurable?

Definitely at least in the first version write the output of **Standardization**. Also as a precaution, if **Conformance** would fail, to have at least the work done saved.
(in subsequent eventual improvements we can make it more sophisticated)

**Comment by AdrianOlosutean** [comment]
Release notes: 
Created a combined job for Standardization and Conformance
