### ISSUE TITLE
Enceladus version is not reported in the logs

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1373]
## Describe the bug
This happens when new helper scripts are used:
```
20/06/03 08:36:36 INFO StandardizationJob$: Enceladus version N/A
```

This happens since we replace `application.conf` during the execution. We need to place Enceladus version into `reference.conf`. #1344 might solve it.

## To Reproduce
Run a test job on DEV or UAT

## Expected behaviour
The Enceladus version should be shown in the log.

**Comment by AdrianOlosutean** [comment]
I would say #1344 solved it

**Comment by Zejnilovic** [comment]
![image](https://user-images.githubusercontent.com/17467768/90220433-79a23680-de08-11ea-84d1-8622e11e0f7e.png)
