### ISSUE TITLE
Make first checkpoint in _INFO file optional

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1378]
## Background
Generating the initial _INFO file causes problem and consume too much resources for some teams. And the value of such control measures is questionable. Consider an option to simplify the process, make the original input optional.

## Feature
Details to be specified

## Related to
* [Atum task](https://github.com/AbsaOSS/atum/issues/35)

**Comment by AdrianOlosutean** [comment]
It seems like specifying the checkpoints with an empty controls field seems to work. You can write something like:
`{"metadata":{"sourceApplication":"",...
,"additionalInfo":{}},"checkpoints":[{"name":"Source","processStartTime":"10-8-2020 00:35:25","processEndTime":"10-8-2020 00:35:25","workflowName":"Source","order":1,"controls":[]},{"name":"Raw","processStartTime":"10-8-2020 00:35:25","processEndTime":"10-8-2020 00:35:25","workflowName":"Raw","order":2,"controls":[]}]}`

**Comment by benedeki** [comment]
## Fields changed once per dataset

* `<SourceApplication>` - name of the application
* `<Country>` - country the file belongs to
* `<SourceType>` - source type
* `<ColumnName>` - ideally the key column name, but can be any column

## Fields (possibly) changed for every run

* `<Filename>` - source file name
* `<Version>` - version of the source file
* `<Date>` - date of the input processing

[_INFO_file_template_minimal.txt](https://github.com/AbsaOSS/enceladus/files/4845570/_INFO_file_template_minimal.txt)

[_INFO_file_template_recommended.txt](https://github.com/AbsaOSS/enceladus/files/4845571/_INFO_file_template_recommended.txt)

**Comment by benedeki** [comment]
Let's put it into our repo - both template files (perhaps with `json` extension for proper coloring?) and a `README.md explaining` the "variables"
Additional improvements:
* variables for `processStartTime` and `processEndTime` in recommended template
* keep country in recommended only (if it works without it)
* version int or string?

**Comment by AdrianOlosutean** [comment]
Release Notes:
Added _INFO file minimal and recommended templates to **Examples** and documented it in the README
