### ISSUE TITLE
Improve ConfigReader

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1391]
## Background
Methods defined in `ConfigReader` depend on `Config` and instantiate it using 
```
private val config: Config = ConfigFactory.load()
```

## Feature
**Suggestion by @benedeki:** What about making it a class (with config input of constructor) and the companion object implementing the class. Like:
```
class ConfigReader(private val config: Config) {
}

object ConfigReader extends ConfigReader(ConfigFactory.load())
```
Would help testing among other.

## Additional context
In addition,
 - Add [more] unit tests for this set of methods.

**Comment by Zejnilovic** [comment]
From #471 :

> ## Background
> We should create an object for properties we get from the property file. This object should then handle validations and possibly default values.
