### ISSUE TITLE
Conflicting dependency on 'enceladus-utils:1.7.0'

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1393]
## Describe the bug
Currently, `spark-jobs` depends on `enceladus-fixedWidth:1.7.0` which depends on 'enceladus-utils:1.7.0'. This creates a class path conflict between current `utils` module and the old `enceladus-utils` which have the same namespace of packages.

## To Reproduce
Inspect the dependencies of `spark-jobs`.

Or (worked for me, but might not always work since class name resolution might be non-deterministic)

Try to go to the source code of `SparkTestBase` from any unit test suite that uses it.

## Expected behaviour
The `spark-jobs` module should depend only on one version of `utils`.

## Screenshots
![Screenshot 2020-06-12 at 09 42 24](https://user-images.githubusercontent.com/4082463/84483553-c8611200-ac99-11ea-9ef3-24a48418fd53.png)

## Proposed solution
We can do either of these:
- Remove `enceladus-fixedWith` dependency if nobody uses it.
- Revive `fixed-width` (yes, with the new name) in `enceladus` project.
- Revive `fixed-width` in a separate repository. This might require removing its dependency on Enceladus utils.

**Comment by Zejnilovic** [comment]
Release Notes:
Update version of FIxedWidth and add charset, treatEmptyValuesAsNulls and nullValue options.
