### ISSUE TITLE
Improve helper scripts to run custom JARs

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1400]
## Background
Currently, the JAR corresponding to Standardization and Conformance jobs is configured in `enceladus_env.sh`. For development and testing it would be very useful to override the location of the JAR so that SNAPSHOT versions be easier to test.

## Feature
Check an environment variable `SPARK_JOSB_JAR` (the name is deliberately very short) in helper scripts. If it is defined, use the specified JAR instead of ones defined in `enceladus_env.sh`.

The workflow of a dev will be like this:
1. Scp a snapshot jar to the user's home folder.
2. Login to the env.
3. Run `export SPARK_JOBS_JAR=/path/to/jars/in/the/home/folder/spark-jobs.jar`
4. Run `run_standardization.sh` or `run_conformance.sh` as usual. The custom JAR will be used.

**Comment by yruslan** [comment]
So people have pointed out that we have '--jar' option that does what is needed.
Maybe I forgot about it when wrote this issue 😛 , or maybe the '--jar' option was in parallel issue.

Nevertheless, an environment variable that overrides the jar might still be useful since sometimes we don't have access to the command line. For instance, if the job is run from customized scripts.

**Comment by AdrianOlosutean** [comment]
Release notes:
Added ability to specify the jar as an environment variable using SPARK_JOBS_JAR_OVERRIDE in helper scripts
