### ISSUE TITLE
Make the number of final partitions written in spark jobs configurable

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#1420]
Let's repartition the data into a number of partitions configurable during the submission of the job. This should apply to both std & conf and provide some sensible defaults.

**Comment by dk1844** [comment]
@DzMakatun

**Comment by dk1844** [comment]
https://github.com/AbsaOSS/enceladus/commit/f73da957ae9599cdce1496928315102ad07269eb I have tested to work as requested, but all this may get superseded by @DzMakatun's dynamic partitioning instead.

**Comment by DzMakatun** [comment]
Spark's [Adaptive execution](https://databricks.com/blog/2020/05/29/adaptive-query-execution-speeding-up-spark-sql-at-runtime.html) repartitions data based on estimated partition size. It is a preferable way, as it adjusts number of partitions with respect to actual data size. Also if works with shuffle operations.

Having number of partitions as an external parameter would require users to estimate the output size and adjust the parameter for each job individually. When set incorrectly, the parameter may result in task skew among executors. 

Below are the results of earlier experiments

<img width="1167" alt="Screen Shot 2020-07-09 at 13 21 03" src="https://user-images.githubusercontent.com/8556576/87034272-deee8080-c1e7-11ea-8ebc-bdcf5a631ce4.png">
<img width="1213" alt="Screen Shot 2020-07-09 at 13 21 56" src="https://user-images.githubusercontent.com/8556576/87034298-eada4280-c1e7-11ea-85fc-2064e9818b01.png">

In the new helper scripts adaptive execution is enabled together with DRA by default. It also can be enabled separately in enceladus_env.sh
ADDITIONAL_SPARK_CONF="--conf spark.dynamicAllocation.enabled=true --conf spark.sql.adaptive.shuffle.targetPostShuffleInputSize=134217728"

**Comment by lokm01** [comment]
Very cool, thanks @DzMakatun !!!

**Comment by dk1844** [comment]
@DzMakatun the  [Adaptive execution](https://databricks.com/blog/2020/05/29/adaptive-query-execution-speeding-up-spark-sql-at-runtime.html) link mentions being available in their _Databricks Runtime 7.0_. Does this mean that there are some other requirements needed to be able to use AQE or just Spark 3.0 will do (with the configuration switches you have posted)?

**Comment by dk1844** [comment]
@lokm01 @DzMakatun is this functionality needed at all (otherwise we close it now) or do we want the fixed-number-repartitioning present alongside to the adaptive approach (and make it switchable by e.g. cmd switch as suggested by @benedeki)?

**Comment by DzMakatun** [comment]
Lets's encourage the usage of the new helper scripts as much as possible and  let's close this.
