### ISSUE TITLE
Run conf & std on EMR (HDFS) - spark-2.4.5 (EMR)

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1426]
## Background
After having menas working in Cloud, we would like to run Enceladus there.

## Feature
Run Standardization and Conformance in EMR.

Solution Ideas 
1. Run Standardization on EMR
2. Run Conformance on EMR
3.

**Comment by AdrianOlosutean** [comment]
I successfully ran Standardization, Conformance and StandardizationAndConformance on EMR with HDFS. The next step would be configuring S3 instead of HDFS in EMR
