### ISSUE TITLE
Update Menas properties to be more containerisation friendly

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1434]
## Background
We are moving Menas towards containerisation. This forces us to update Menas a bit.

## Feature
update Menas's properties to be more containerisation friendly. Passing huge JAVA_OPTS environment variable is not sustainable.

## Proposed Solution [Optional]
Solution Ideas 
1. Allow Menas properties to be taken from env variables
2. 
3.

**Comment by Zejnilovic** [comment]
SpringBoot offers reading from environment variables out of the box. Currently looking for the best way to package our docker image

**Comment by benedeki** [comment]
Release notes:
Updated Menas properties to be more containerization friendly.
