### ISSUE TITLE
runPostProcessing could throw warning with no meaning

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1443]
## Describe the bug
`runPostProcessing` in `CommonJobExecution` can throw out a warning which is connected to a piece of code that could not even run in the end.

## Expected behaviour
Have the `log.warn` in conditional, not running it if there's no reason to.

## Additional context
Needs #1377 to be merged

**Comment by AdrianOlosutean** [comment]
Release notes:
Fixed potential erroneous runPostProcessing warning
