### ISSUE TITLE
Helper script for combined Standardization&Conformance job

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1465]
## Background
After refactoring it's possible to run Standardization and Conformance in succession in one go.

## Feature
Create a helper script that call the new combined Standardization&Conformance job main function.

**Comment by benedeki** [comment]
Update the README.md to mention the new script as well.

**Comment by AdrianOlosutean** [comment]
Release notes:
Created helper script for the combined Standardization and Conformance job and updated README with information about the new job
