### ISSUE TITLE
It's possible to delete the original column with Drop Conformance Rule

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1480]
## Describe the bug
By the original paradigm it should not be possible to modify the original data within Conformance. But it is possible to delete the original columns using Drop Conformance Rule

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Go to Menas -> Conformance Rules
2. Create a new conformance rule
3. Choose Drop Conformance Rule and enter an original dataset column as its parameter
4. Save
5. Execute Conformance
6 It passes

## Expected behaviour
It should not be possible to drop the original column

**Comment by benedeki** [comment]
I would consider a setting into `application.conf` allowing the delete, defaulting to `false` (not allowed).
This would make it possible for those, who have a reasonable requirement for the drop to do so.

**Comment by Zejnilovic** [comment]
Release Notes:
Add a check for Conformance Rules that they are not trying to modify a column from the original schema. If this is desired user can use option `conformance.allowOriginalColumnsMutability ` and set it to true. In that case, it will only print a warning.
