### ISSUE TITLE
Alternate helper script to run in a less resource intensive manner

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1481]
## Background
When the helper scripts wait for completion they don't do it the most efficient way.

## Feature
Consider implementing polling instead active waiting for the spark job to finish within the helper scripts

## Proposed Solution
See attached file
[SparkDisconnected.sh.txt](https://github.com/AbsaOSS/enceladus/files/5054047/SparkDisconnected.sh.txt)

**Comment by AdrianOlosutean** [comment]
Release notes
Running Spark jobs disconnected on cluster mode for better edge node resource usage

**Comment by AdrianOlosutean** [comment]
Release notes:
Run Enceladus disconnected in cluster mode for better edge node usage
