### ISSUE TITLE
Add a strict parsing mode to Decimal type.

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1482]
## Background
When a string is parsed to Decimal type, in case the string contains more decimal places then the Decimal's scale parameter the extra decimal places are trimmed.

## Feature
Implement a strict parsing option - triggered by metadata entry, defaulting to `false` - that will generate an error in `ErrCol` in case the decimal places overflow the scale of the define Decimal type.

## Example
Under strict rule the parsing would be as follows:
Decimal(10,2)
"123.45" -> 123.45, no error in `ErrCol`
"1234,567-> 1234.56, error in `ErrCol`

**Comment by AdrianOlosutean** [comment]
Release notes
`strict_parsing` on Decimal type will error when the number of digits in the value is higher than the defined scale in the type
