### ISSUE TITLE
When connecting to secure schem registry, it doesn't pick up the correct certificate

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1496]
## Describe the bug
On the Dev environment, when running Menas it's not able to connect to secure schema registry.

## To Reproduce
On the Dev environment (not a local run) try to get a schema from secure schema registry. The logs suggest not the correct certificate is selected, therefor authentication fails.

## Expected behaviour
Secure schema registry works.

## Additional context
Consider to add more logging to figure out what's happening.
Some hints might be found in https://stackoverflow.com/questions/5292074/how-to-specify-outbound-certificate-alias-for-https-calls

**Comment by dk1844** [comment]
Release notes:
Secure Schema Registry fix - TrustStore & KeyStore for SSR is now loaded programmatically and directly used for the integrating connection (instead of relying on environment variables)
