### ISSUE TITLE
Print JAR version on --help options

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1509]
## Background
When people run --help command they should see a Standardization/Conformance version as well

## Feature
when --help is invoked print something like

```
Standardization version 10.20.30
Job Parameters
Usage: Standardization Job [options]
```

**Comment by benedeki** [comment]
Somewhat related to #1510

**Comment by AdrianOlosutean** [comment]
Release notes
Running `--help` prints the project version as well
