### ISSUE TITLE
Enceladus - SparkJobs version should not be overrideable

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1510]
## Background
The version of the project is injected from Maven pom file via `application.conf`/`application.properties`.

## Feature
The way how it is done, it is possible to override the version via command line. Would be better to make it hard-coded without the possibility to be influenced by the user.

## Proposed Solution
Check for inspiration https://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code/3697482

**Comment by benedeki** [comment]
Somewhat related to #1509

**Comment by AdrianOlosutean** [comment]
Release notes
Enceladus SparkJobs version is taken from runtime instead of from `application.properties`, so it cannot be overridable
