### ISSUE TITLE
Menas version should not be overrideable

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1530]
## Background
The version of the project display in UX as well is injected from Maven pom file via `application.properties`.

## Feature
The way how it is done, it is possible to override the version via command line. Would be better to make it hard-coded without the possibility to be influenced by the user.
Menas already displays the version. Only the way how it is obtained need to be changed.

## Proposed Solution
Check for inspiration https://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code/3697482

**Comment by benedeki** [comment]
See `menas.version` in `application.properties` and `WebSecurityConfig` class

**Comment by AdrianOlosutean** [comment]
Shouldn't `UserInfoController` also be changed? I tried changing it but it fails

**Comment by benedeki** [comment]
> 
> 
> Shouldn't `UserInfoController` also be changed? I tried changing it but it fails

Yes of course. How does it fails?

**Comment by AdrianOlosutean** [comment]
Release notes
Menas is taking the version from the project runtime instead of `application.properties`, thus its version is not overridable
