### ISSUE TITLE
Dataset - Monitoring - Run Details - shows wrong end time

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1536]
## Describe the bug
Monitoring (Dataset tab) shows run end time with presumably bad timezone.

## To Reproduce
Steps to reproduce the behaviour OR commands run:
1. Run full std and conf
2. Check Run 
3. Check Monitoring tab
4. Compare end times

## Expected behaviour
Either everything should be timezone or nothing. Ideally, it should be as is in _INFO file

### Monitoring
![image](https://user-images.githubusercontent.com/17467768/94660883-95a15f00-0306-11eb-819a-633bd588d176.png)
### Run Detail
![image](https://user-images.githubusercontent.com/17467768/94660935-a5b93e80-0306-11eb-82ce-5433b405d328.png)

**Comment by DzMakatun** [comment]
Release note:
Fixed a bug in shown time in Monitoring. Both 'Run Start" and 'Latest checkpoint End time' are now shown in browser's timezone.
