### ISSUE TITLE
CommonJobExecution.runPostProcessing performance improvement proposal

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1538]
## Background
`CommonJobExecution.runPostProcessing` reads a parquet ([link](https://github.com/AbsaOSS/enceladus/blob/develop/spark-jobs/src/main/scala/za/co/absa/enceladus/common/CommonJobExecution.scala#L113)) that is an output of std or conf. This parquet (actually `Dataframe`) can be supplied by `process"Type"Result` (conformance or standardization). Weirdly `processStandardizationResult` returns a `DataFrame`, but conformance doesn't.

## Feature
Align the usage of `process"Type"Result` method and don't read again the written parquet in `runPostProcessing`

**Comment by benedeki** [comment]
The situation is actually more complicated. It relates to the (in-)stability of computation within a distributed cluster.
It should definitely be addressed though - to make it consistent here at least.
Let's discuss it with @yruslan too and consider solutions for S3 (and its costs)

**Comment by dk1844** [comment]
Release notes:
processStandardizationResult & processConformanceResult force postProcessing to reread data written to disk to avoid possible data instability

**Comment by dk1844** [comment]
Do we close this issue and the future ones will just be linked? @benedeki @Zejnilovic

**Comment by Zejnilovic** [comment]
I think you can. So we have "nice" release notes. Next issue might be broader and be done during our "audit" time.

**Comment by benedeki** [comment]
Yup, let's close it. 👍
