### ISSUE TITLE
Design Dataset Properties Feature

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1568]
Design and agree how to Dataset Properties feature should look like.
The description should be clear enough, to be able to implement the further Issues within the Epic

**Comment by benedeki** [comment]
Design suggestion:

Introduction
============

Dataset properties is a map attached to a Dataset.

The keys of the map are defined on application setup level. They are common to
all Datasets of the deployment.

The values then are entered by users and are specific per each Dataset.

Property definition
===================

| **Definition field**   | **Field type** | **Description**                                                                         |
|------------------------|----------------|-----------------------------------------------------------------------------------------|
| id_property_name\*     | String         | The actual name of the additional property                                              |
| type                   | Enumeration    | Type of the property – what kind of values can be assigned to the value of the property |
| description            | Text           | Clear description what the property represents                                          |
| default_value          | String         | The default value of the property to use in the datases                                 |
| put_into_info_file     | Boolean        | Flag, if the property should be put into each \_INFO file upon data processing          |
| mandatory              | Boolean        | Flag to indicate the property has to be defined for data to be processed                |
| type_specific_settings | Json           | Some types might use or even require additional settings. See bellow.                   |

*Property_name* is the unique key of the definition.

Property types
--------------

-   String

-   Integer

    -   Additional settings: *min*, *max*

-   Float

    -   Additional settings: *min*, *max*

-   Boolean

-   Date

    -   Additional settings: *min*, *max*

-   Timestamp

    -   Additional settings: *min*, *max*

-   Selection/List

    -   Additional settings: *items*

-   List/Array/Set

    -   A set of values. E.g. tags

Storage of Properties Values
============================

The values of the properties could be stored as a Map within Dataset. But it
seems more effective and more modular to keep them in a separate table.

The suggested table fields:

| key_dataset       | String    |
|-------------------|-----------|
| key_property_name | String    |
| property_value    | String    |
| last_change       | Timestamp |

Menas
=====

Menas will provide a set of new APIs to read the configuration of the
properties. And then read and write the property values of the Dataset.

New API
-------

`{dataset}/properties/definitions`

GET request to get all properties’ definitions.

`{dataset}/properties/values`

GET request to get all properties’ values.

Advanced: query parameters could define filtering.

`{dataset}/properties/value/{propertyName}`

CRUD API to read, add, modify and delete properties’ value

Changes in existing API
-----------------------

When a Dataset with missing properties is requested, return an error response.
Probably *406 Not Acceptable*.

The content should still be there to allow UI to operate on it!

Alternatively there could be a

SparkJobs
=========

Two tasks for *SparkJobs*:

1.  Handle if the Dataset response API signals some mandatory properties are
    missing.

2.  Het all the properties and values to be added to \_INFO file and ensure,
    they are there.

UI
==

Based on the properties definition it would create controls to edit the
properties’ values.

It would display a comprehensive list of Dataset’s properties and their values.

Show a distinct label if mandatory properties are not defined (thus processing
would not succeed).

Open questions
==============

Where to store the configuration?
---------------------------------

Could be either some configuration file or the application DB. Database seems
preferable.

Should this be core part of Means or a plugin?
----------------------------------------------

Ideally it would be a plugin, actually tthre plugins. One for Means, one for UI
and one for SparkJobs. The needs of three plugins makes it little bit
complicated.

Should they be just declaratory or functional? Tags vs properties
-----------------------------------------------------------------

It’s more about naming. *Properties* suggests possible functional use, *tags*
sounds more declaratory.

Create CRUD API for properties definition?
------------------------------------------

Probably eventually yes. Probably not be needed in the first iteration.

What if there are extra properties for the Dataset than the defined ones?
-------------------------------------------------------------------------

Eventually the properties definition API should handle it fully. Until then,
ignore.

Keep history of property definitions?
-------------------------------------

Keep history of property values?
--------------------------------

Have three levels of mandatory value? Optional, recommended, mandatory (if missing = OK, Warning, Error)?
---------------------------------------------------------------------------------------------------------

Might be over-engineering.

**Comment by dk1844** [comment]
The suggested
```
GET {dataset}/properties/definitions
GET {dataset}/properties/values
GET, POST, PUT, DELETE {dataset}/properties/value/{propertyName}
```
look good on the first glance, but it may become quite cumbersome to get to the definition and value of a single property if the property list is longer. How about an alternative of:
```
GET, POST, PUT, DELETE {dataset}/properties/{propertyName}/value
GET, POST, PUT, DELETE {dataset}/properties/{propertyName}/definition
GET {dataset}/properties/{propertyName}
```
with the last you could easily view both the value and definition at once, e.g.
```json
{
  "value": ...,
  "definition": ...
}
```
On the other hand, do we need to provide endpoints to _get/write all definitions_ or _get/write all values_ at-once?

**Comment by benedeki** [comment]
Definitions are global. So no need to access them via dataset. That is actually a mistake. And therefore not sure it make sense to return definitions and values at once.
Also there is the `properties/values` to get all the values at once. No need to go one by one.
Definition won't have write, at least not for now. Eventually yes, but under admin authorization (so we need authorization to work ;-) )
Let's discuss in the GDoc document. And once agreed only copy it here.

**Comment by benedeki** [comment]
Declaration
===========

Pilot phase implementation

Future phase implementation

Introduction
============

Dataset properties is a map attached to a Dataset.

The keys of the map are defined on application setup level. They are common to
all Datasets of the deployment.

The values then are entered by users and are specific per each Dataset.

Property definition
===================

This is a record to define one property within the application. If there needs
to be multiple properties, each would be defined on one “row”

| **Definition field**   | **Field type**                                                     | **Description**                                                                         |
|------------------------|--------------------------------------------------------------------|-----------------------------------------------------------------------------------------|
| property_name\*        | String                                                             | The actual name of the additional property                                              |
| property_type          | Enumeration (string, one of the types described bellow this table) | Type of the property – what kind of values can be assigned to the value of the property |
| description            | Text                                                               | Clear description what the property represents                                          |
| suggested_value        | String                                                             | The value suggested on first entry of the property                                      |
| put_into_info_file     | Boolean                                                            | Flag, if the property should be put into each \_INFO file upon data processing          |
| essentiality           | optional/recommended/mandatory                                     | Flag to indicate the property has to be defined for data to be processed                |
| type_specific_settings | Json                                                               | Some types might use or even require additional settings. See bellow.                   |
| disabled               | Boolean                                                            | “Deletion” flag                                                                         |

*Property_name* is the unique key of the definition.

Property types
--------------

-   String

-   Integer

>   o   Additional settings: *min*, *max*

-   Float

>   o   Additional settings: *min*, *max*

-   Boolean

-   Date

>   o   Additional settings: *min*, *max*

-    Timestamp

>   o   Additional settings: *min*, *max*

-   Time

-   Enumeration

>   o   Additional settings: *items*

-   Set

>   o   A set of values. E.g. tags

-   Map

Storage of Properties Values
============================

Properties would be stored as an optional Map[String, String/Any] field within
the Dataset.

The values of the properties could be stored as a Map within Dataset. But it
seems more effective and more modular to keep them in a separate table.

The suggested table fields:

| key_dataset       | String    |
|-------------------|-----------|
| key_property_name | String    |
| property_value    | String    |
| last_change       | Timestamp |

Menas
=====

Menas will provide a set of new APIs to read the configuration of the
properties. And then read and write the property values of the Dataset.

New API
-------

-   /api/properties GET \# All properties definitions - probably no need to
    implement it yet.

-   /api/properties/datasets GET \# Dataset properties definitions

-   /api/properties/datasets/{propertyName} GET \# Specific dataset property
    definition

-   /api/admin/properties/datasets GET,POST - future

-   /api/admin/properties/datasets/{propertyName} PUT,GET,DELETE - future

GET request to get one particular property definitions.

-   /api/dataset/{datasetName}/{datasetVersion}/properties/

GET request to get all properties’ values.

Advanced: query parameters could define filtering.

?put_into_info_file=true

-   /api/dataset/{datasetName}/{datasetVersion}/properties/{propertyName}

CRUD API to read, add, modify and delete properties’ value

-   /api/dataset/{datasetName}/{datasetVersion}/valid

    -   Response: {“valid”: true \| false, “errors”: ...?} 

-   /api/dataset/{datasetName}/{datasetVersion}

    -   =\> {... all the dataset key/values …, “valid” : true}

Changes in existing API
-----------------------

No need of change of existing APIs has been observed.

SparkJobs
=========

Two tasks for *SparkJobs*:

1)  Call /api/dataset/{datasetName}/{datasetVersion}/valid and if false stop the
processing.

2)  Get all the properties and values to be added to \_INFO file and ensure they
are there. (See filtering on
/api/dataset/{datasetName}/{datasetVersion}/properties/)

UI
==

Based on the properties definition it would create controls to edit the
properties’ values.

It would display a comprehensive list of Dataset’s properties and their values.

Show a distinct label if mandatory properties are not defined (thus processing
would not succeed).

Open questions
==============

Where to store the configuration?
---------------------------------

Could be either some configuration file or the application DB. Database seems
preferable.

**IN DB**

Should this be the core part of Means or a plugin?
--------------------------------------------------

Ideally it would be a plugin, actually there plugins. One for Means, one for UI
and one for SparkJobs. The needs of three plugins makes it a little bit
complicated.

**Currently NOT a plugin :-(**

Should they be just declaratory or functional? Tags vs properties
-----------------------------------------------------------------

It’s more about naming. *Properties* suggest possible functional use, *tags*
sounds more declaratory.

Create CRUD API for properties definition?
------------------------------------------

Probably eventually yes. Probably not needed in the first iteration.

What if there are extra properties for the Dataset than the defined ones?
-------------------------------------------------------------------------

*Valid = false, automation on removal is needed.*

**Valid = true, can stay, and probably should.**

Keep history of property definitions?
-------------------------------------

**Right now happy with Disabled flag**

Keep history of property values?
--------------------------------

**Comes with Dataset history**

Have three levels of mandatory value? Optional, recommended, mandatory (if missing = OK, Warning, Error)?
---------------------------------------------------------------------------------------------------------

**Want three levels.**
