### ISSUE TITLE
Data Model for Dataset properties

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1569]
## Background
Dataset properties is a map attached to a Dataset.
The keys of the map are defined on application setup level. They are common to all Datasets of the deployment.
The values then are entered by users and are specific per each Dataset.

## Feature
Design the data model for dataset properties (individual dataset specific) and dataset properties definitions (env-wide).
Create the Dataset Definition Collection in MongoDB for stored data.

**Comment by Zejnilovic** [comment]
**Question** - if we create another collection for this "relational data" to Dataset, won't this go against the principles of the Document based DB.

**Comment by benedeki** [comment]
> 
> 
> **Question** - if we create another collection for this "relational data" to Dataset, won't this go against the principles of the Document based DB.

Yes, perhaps for the property values (map: name->value) . But for property definitions we will definitely need it.

**Comment by dk1844** [comment]
Release notes:
Dataset properties (per dataset) and property definitions (system-wide) support has been added (pilot phase), it is REST managed without UI for now.
