### ISSUE TITLE
Menas API for Dataset properties - pilot property Data Classification

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1570]
## Background
Dataset properties is a map attached to a Dataset.
The keys of the map are defined on application setup level. They are common to all Datasets of the deployment.
The values then are entered by users and are specific per each Dataset.

## Feature
Implement the Menas API per the design, fulfulling the needs to serve the pilot Dataset property - _Data Classification_.
Also add the specific configuration

### Data Classification
* Selection from a given list
* Consider it Mandatory
* Consider writing it to _INFO file

**Comment by Zejnilovic** [comment]
**Question** - do we export them as part of import/export feature, do we export them together with the dataset, what do we do if the "second" Menas does not have the same map defined?

**Comment by benedeki** [comment]
Very good questions.
In first iteration, the pilot I would skip the properties import/export. 
Sugegestion: Eventually add it. On import then skip the extra properties and well, the missing ones remain missing. (Same as adding a new property definition. Right after that it will be missing in all datasets.)

**Comment by Zejnilovic** [comment]
After the implementation of #1569 we added the properties even in the Dataset so to close this issue only some small updates are needed:

- [ ] Allow supplying of properties on create or edit methods
- [ ] On export, export properties as an object with key-value pair or as an array of objects with a single key-value pair.

**Comment by Zejnilovic** [comment]
Release Notes:
Properties now can be added to dataset on create, edit or import. They are expected as an object of key-value pairs. Export function exports them as the same.
