### ISSUE TITLE
Ensure that when --help is run, no other code will precede it

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1579]
## Background
Currently when user runs the `--help` there is some validation that is run before the actual `scopt help`. We need to ensure that when users run `--help` they don't trigger a series of events before that.

## Feature
Ensure that when `--help` is run, no other code will precede it

**Comment by AdrianOlosutean** [comment]
Release notes
Parameters processing is run first, so help would be faster
