### ISSUE TITLE
Mapping table filtering

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1603]
## Background
Many of the mapping tables are way too big, preventing _broadcast_ strategy to be used/used effectively. Furthermore  even the standard method of application would be more effective, if known unused values are filtered out before-head.
Particularly it has been observed that often a _lit_ column is added in Conformance of a dataset to allow proper matching. Filtering would eliminate such step.

## Goal
Allow filtering of mapping tables on their definition and/or when used in mapping conformance rule

## Expected Task List
A list of expected issues that will be needed to achieve this Epic
1. Filtering of mapping table withing it's defintion
2. Filtering of mapping table when used in Mapping Conformance Rule
3. UI to enable the definition of the filter

**Comment by dk1844** [comment]
Release notes:
DataFrameFilter BSON serialization fixed.
