### ISSUE TITLE
Integration Tests to ensure the on prem and AWS branches functionality was not lost

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1625]
## Background
2.18 will be a merge of cloud and develop branches and will require a deeper look and more tests. 

## Test 
(on both cloud and local)

- [ ] Create a Dataset with a Mapping table conformance rule
  - See that the HDFS browser is working as expected
  - See that Oozie tab is working as expected
- [ ] Run spark-jobs.jar full
- [ ] Check on the output of the std & conf
  - Check Atum _INFO files
  - Check the outputted data
  - Check the Run object
  - Check Spline

**Comment by HuvarVer** [comment]
Release notes:
Now it is possible to populate test data into HDFS and mongo by bash scripts. Data are part of the codebase. It is possible to run tests from codebase with test JSONs using Hermes 0.3.1
