### ISSUE TITLE
Dump Spline lineage next to data as _LINEAGE

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1626]
## Background
Spline from version 0.4 does not write lineage into a file next to data any more. But this should be something doable as this use case was already solved on a per-project basis. Talk to Spline team for more.

## Feature
Extend spline agent to dump lineage as JSON next to the data into the _LINEAGE file

**Comment by benedeki** [comment]
Solved by _LINEAGE dumper_ created by _Spline_ team and enhanced by #1733
