### ISSUE TITLE
Add hide functionality to the HDFS (file) browser component

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1627]
## Background
There might be cases when HDFS (file) browser might not be able to connect to HDFS or S3, but Menas should still have full functionality as a metadata store of sorts

## Feature
Add hide functionality to the HDFS (file) browser so if it is unable to read files, let the user just specify them by hand in the text box above.

**Comment by dk1844** [comment]
Release notes:
Entering HDFS/S3 paths can now be done either using the existing HDFS Browser or via a simple input field. The mode is chosen automatically on dialog open and can be switched manually back and forth.
