### ISSUE TITLE
Multiple outputs from spark-hats

### ISSUE THREAD

**Issue by AdrianOlosutean** [AbsaOSS/enceladus#1663]
This is a placeholder issue for possible changes needed in `spark-hats`.
And the eventual upgrade of the version within Enceladus.

**Comment by benedeki** [comment]
I would consider this a last item in the Epic. I believe BE can do the multiple columns evaluation in a sequence of hats calls, instead of getting them all at once.
Less effective, but by a constant, and allowing the feature to work.

**Comment by AdrianOlosutean** [comment]
The newsest [spark-hats 0.2.2](https://github.com/AbsaOSS/spark-hats/releases/tag/v0.2.2) release implemented `nestedUnstruct` which greatly helps in this regard
