### ISSUE TITLE
Mapping conformance rule allowing for 8 or more joins

### ISSUE THREAD

**Issue by zakera786** [AbsaOSS/enceladus#1694]
## Background
We currently have a restriction that allows only 5 join conditions

## Feature
Users require a minimum of 8 join conditions i.e 8 data columns

**Comment by benedeki** [comment]
We can take it up to 10. It's really unlikely that more would be needed, especially with the filtering in place.

**Comment by AdrianOlosutean** [comment]
Release notes
Mapping conformance rule supports up to 10 join conditions
