### ISSUE TITLE
Save original timezone information in metadata file

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#172]
## Background
Currently, we transform and save all standardized timestamps and dates as `UTC`. However, this loses us the information of the original data's timezone. This information is only accessible in the Menas schema for the given dataset. Which is not the most convenient place to check when, for example, doing preliminary analysis of the output data in the spark-shell

## Feature
The lost timezone information could prove very useful for data access and is worth preserving along with the data without reliance on Menas.

## Proposed Solution [Optional]
We can save this timezone information is the `_METADATA` file

**Comment by GeorgiChochov** [comment]
@benedeki Wasn't this one implemented already or am I getting confused?

**Comment by benedeki** [comment]
Well, except the _Save the information within the metadata file._ which would be useful for any presentation efforts of data.
I think it's relatively closely related to #174

**Comment by GeorgiChochov** [comment]
Updated the description to reflect that.

**Comment by benedeki** [comment]
Release notes:
The applied default time zones are written into _INFO file.
Upgrade of [Atum](https://github.com/AbsaOSS/atum) to version 3.6 and [Absa Commons](https://github.com/AbsaOSS/commons) to 0.0.27.
