### ISSUE TITLE
Spline _LINEAGE dumper to work on S3

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1733]
## Background
Spline is able to write the lineage to HDFS. With migration to AWS we need to ensure this feature works on S3 as well.

## Feature
Enhance, if needed, [Spline Dumper](https://github.com/AbsaOSS/spline-spark-agent/issues/174) and Enceladus to write to S3.

## Proposed Solution
Perhaps could be solved similarly as Atum, with optional libraries to include when S3 is to be supported.

**Comment by dk1844** [comment]
Release notes
Spline agent 0.6.0 integrated - support for `_LINEAGE` file generation is present.
