### ISSUE TITLE
Properties suggested value is applied automatically and it's not optional

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1784]
## Describe the bug
Part of property definition is a suggested value. For enumeration it actually have to be an item from the list.
When editing a dataset and the property has not be defined the suggested value is used and accepted. And the suggested value is not optional.

Also empty string is accepted as a valid property value, which is strange.

## To Reproduce
1. Have some properties defined, with a non-trivial suggested value, set as _Mandatory_
2. In _Menas_ create new dataset. Save the dataset without changing the suggested value
3. It's accepted
4. This might not be desirable, at least not in all cases

## Expected behavior
Suggested values are not applied automatically, at least not always.

## Suggested solutions
* Make suggested value optional
  * Empty string should serve well
  * Maybe conversion to `Option[String]` might not cause problems either
* Make empty string to be seen as undefined value for property
* **_Bonus:_** use suggested value in Menas UI controls as real suggestions, not a value directly

**Comment by dk1844** [comment]
Release notes
Dataset property values are now suggested instead of prefilled; suggested values are optional in the system. The optionality of enum-property fields in now fixed.
