### ISSUE TITLE
HDFSBrowser component stuck after folding root structure

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#179]
**Describe the bug**
In Menas Dataset creation/editing, in a HDFSBrowser component, if I click to fold the root structure I lose the ability to click any other element in the browser. Then I need to click cancel or save. But if I click cancel I lose the other stuff I wrote in it, and if I click save, I get a version witch point to the root of hdfs.

Gif in Screenshots speaks more than a thousand words.

**To Reproduce**
Steps to reproduce the behavior OR commands run:
1. Go to Menas
2. Open and edit any dataset or create a new one
3. Click to fold the root structure in HDFSBrowser
4. Try to click any other

**Expected behaviour**
I expect to still be able to fold/expand and choose other things.

**Screenshots**
![feb-25-2019 07-43-05](https://user-images.githubusercontent.com/17467768/53319157-fcac9580-38d1-11e9-9aa9-04e11a3b2409.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by lokm01** [comment]
This seems to be fixed in PR #316

**Comment by Zejnilovic** [comment]
Yes, it does. I will close the issue.

**Comment by GeorgiChochov** [comment]
In the future, let's not close issues until their PR is merged.

**Comment by Zejnilovic** [comment]
> In the future, let's not close issues until their PR is merged.

I agree, I thought it already was and when I realized my mistake I was keeping an active eye on it.
