### ISSUE TITLE
Menas sometimes doesn't load Dataset properties' definitions

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1791]
## Describe the bug
Occasionally Menas doesn't load the dataset properties' definitions. Then when editing or creating new dataset controls to edit the properties are not populated. This can cause properties not to be defined for the dataset.

## To Reproduce
This is not always reproducible. The steps are the most probable way:
1. Have some properties defined for Enceladus
1. Open _Menas_ after longer inactivity or in a freshly installed browser
1. Login
1. Click on 'Datasets'
1. Click on `New dataset`
4. See the defined properties not being shown
5. Reload helps

## Expected behaviour
Dataset properties definitions are always properly loaded.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: replicated in several of them (Chrome, Waterfox, Edge, Opera)

**Comment by benedeki** [comment]
This doesn't seem to be a caching issue. Observed on freshly started Appache with Menas. Also in freshly installed browser while the other browser showed the properties at the same time.
More like a race condition on Menas UI startup.

**Comment by Zejnilovic** [comment]
Managed to fish out this

![image](https://user-images.githubusercontent.com/17467768/119349911-04b93280-bc9f-11eb-928d-a744314b291a.png)

But it is hard to simulate (hard refresh with cache removal) and not always.
Fixable by a normal refresh.

**Comment by Zejnilovic** [comment]
A new finding for me is that if I have HDFS off (unable to connect) it never load my properties. Not sure if it is my local problem

**Comment by dk1844** [comment]
I believe the original issue was fixed in https://github.com/AbsaOSS/enceladus/pull/1789, specifically in commit https://github.com/AbsaOSS/enceladus/pull/1789/commits/a39685d1d77fa22718a80b52530fc7e6f367c574.
