### ISSUE TITLE
Error message if I want to use default values while creating dataset

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#181]
**Describe the bug**
If I try to create a Dataset with default values, I get an error message, telling me to choose particular values. So I need to click something else, then click what I want again.

**To Reproduce**
1. Go to any Dataset in Menas
2. Click add button
3. Try to save

**Screenshots**
![image](https://user-images.githubusercontent.com/17467768/53323244-e3a9e180-38dd-11e9-8f31-9f0863c73864.png)

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
- Browser Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by Zejnilovic** [comment]
This becomes worse if we only have one of something. It throws errors that cannot be even found in logs. (On IntelliJ at least). I would like to urge someone to look into this.

![mar-05-2019 18-45-48](https://user-images.githubusercontent.com/17467768/53825628-050e6b80-3f77-11e9-9050-612a69de20c7.gif)

In the gif I am in the situation that I have only one mapping table. So I cannot choose another/different one. Which means it is not going to display the versions correctly and the `save` button doesn't expect a null in the version.

**Comment by GeorgiChochov** [comment]
Picking it up!

**Comment by GeorgiChochov** [comment]
> This becomes worse if we only have one of something. It throws errors that cannot be even found in logs. (On IntelliJ at least). I would like to urge someone to look into this.
> 
> ![mar-05-2019 18-45-48](https://user-images.githubusercontent.com/17467768/53825628-050e6b80-3f77-11e9-9050-612a69de20c7.gif)
> 
> In the gif I am in the situation that I have only one mapping table. So I cannot choose another/different one. Which means it is not going to display the versions correctly and the `save` button doesn't expect a null in the version.

@jozefbakus has actually fixed this as part of #80, which we just merged!
