### ISSUE TITLE
Warnings regarding missing property are logged in Tomcat, not SparkJobs

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1819]
## Describe the bug
When a `Recommended` or `Mandatory(allowRun = true)` property is not defined there should be a warning when the dataset is processed. The warning is there, but it's logged in Tomcat log instead of the executed _SparkJobs_.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Define a property with _Essentiality_ `Recommended` or `Mandatory(allowRun = true)`
2. Create a new Dataset or use an existing one
3. Standardize the Dataset
4. See where the warning log appears

## Expected behaviour
Expected the Warning to appear in the log of _SparkJobs_

**Comment by benedeki** [comment]
Reopening, as some backport PRs are still out there (and missing Release Notes and Release assignment)

**Comment by Zejnilovic** [comment]
Release Notes:
When a recommended or mandatory bu allowed for run property is missing, the `spark-jobs` logs a warning.

**Comment by benedeki** [comment]
Temporary closing to enable release notes generation.
