### ISSUE TITLE
No changes detected in Dataset when property value is changed

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1820]
## Describe the bug
When a property is defined or changed in a Dataset, the version is correctly increased. But the audit log show "no changes".

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Have a property defined
2. Open an existing dataset definition
3. Add a value to the property
4. Save the changes
5. See the version increased
6. Go to Audit tab of the Dataset
7. See _No changes_

## Expected behaviour
The changes are properly displayed in the audit log.

## Screenshots
![image](https://user-images.githubusercontent.com/14905969/122624018-b3824000-d09e-11eb-9d92-4118b07331b1.png)

**Comment by Zejnilovic** [comment]
Release notes:
Now Audit Trail in Menas shows added, removed and changed properties
