### ISSUE TITLE
Switching between models doesn't update correctly the view

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#184]
**Describe the bug**
If I am using links to from one model to another I get wrong views. 

First is Schemas UsedIn link I click to Dataset and in the left menu, I have anything that I had clicked/show before. -> It doesn't update
Then I from Dataset view click a link to the schema and the dataset version I see in there are latest versions, not the ones actually used.

**Screenshots**
![feb-25-2019 09-38-25](https://user-images.githubusercontent.com/17467768/53325102-c4fa1980-38e2-11e9-81c9-002b39698466.gif)

**Desktop (please complete the following information):**
- OS: macOS 10.14.3
- Browser Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by Zejnilovic** [comment]
If it shows the bad version in Used In view it even opens the bad version.

**Comment by lokm01** [comment]
Can't replicate. Has this been fixed?

**Comment by Zejnilovic** [comment]
Can't replicate anymore. Closing
