### ISSUE TITLE
Properties name cut-off

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1842]
## Describe the bug
A dataset property name longer than to fit into the give space is used - which is not very long - the rest of the name is cut off marked with an ellipsis. This doesn't help comprehension at all.

## Expected behaviour
Use more space for the label containing the property name. Consider autoresizing the window to fit the whole name,

## Screenshots
![image](https://user-images.githubusercontent.com/14905969/124733082-22bbb900-df14-11eb-9452-c3995582458e.png)

**Comment by benedeki** [comment]
**Idea/suggestion:**
As resizing the parent window based on the length of the label might be complicated.
What about creating a group box with a caption _Dataset properties:_
Inside would then be properties using the whole width of the window. Furthermore if this extra space is not enough, in case the label is longer, let's put it on its own line, while the edit box and icon bellow it.
And even if that is not enough - IMHO clearly misused name - the whole name could be put into the hint when hovering over the label.

**Comment by dk1844** [comment]
Release notes
Dataset properties editing UX has been enhanced - now, there is more room for the property name, a useful tooltip is provided and the dialog is resizable (Small by default).
