### ISSUE TITLE
Create a summary page for datasets missing properties

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1843]
## Background
It's not easy to identify which datasets are missing properties.

## Feature
Create a summary page listing the datasets that are missing _Mandatory_ and _Recommended_ properties, so it's easy to fix them

## Proposed Solution
Some summary page with statistics and listing of datasets having these issues. Ideally with click-through to the dataset.

**Comment by AdrianOlosutean** [comment]
I'm wondering where to get to this page from? I would say from Home, since it seems something of high importance.

**Comment by AdrianOlosutean** [comment]
Release notes
Home page with properties, number of missing Mandatory and Recommended properties, side panel with number of datasets missing each property and property page with tab containing a list of datasets missing the property
