### ISSUE TITLE
Remove the ability to set a datset filter via the configuration file

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1867]
## Background
When the UI will have been done, the ability to set the dataset filter via the configuration the more disruptive and confusing rather than helping.

## Feature
Remove the ability to set the dataset filter via the configuration file.

## Proposed Solution
Solution Ideas 
1. See the class `FilterFromConfig` and its usage.

**Comment by dk1844** [comment]
Release notes
Enceladus no longer support loading filter from config (config tree `dataframefilter.$dataFrameName`).
