### ISSUE TITLE
Migration application/script

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1876]
## Background
As part of moving Enceladus to cloud, we need to get the existing configuration (dataset definitions) data to AWS.

## Feature
Create the application that will migrate - read, transform and write elsewhere (in cloud) the data of selected datasets

**Comment by dk1844** [comment]
Some questions:

1. I assume this only involves metadata (whatever is in Menas), we are not moving the actual data on HDFS/S3. Correct me if I am wrong (CMIIAW).
2. I assume this should involve reaching to the underlying mongos, not using any of the Menas API. CMIIAW
3. Is the target guaranteed to have the collections already or should the migration account for collection creation, too?
4. Collections are versioned, current collection version is _1_. What about the older collections (assumption: do not migrate)?
5. All v1 collections are to be migrated except for `landing_page_statistics_v1` (makes no sense if data are filtered). Or migrate if not filtered?
6. Data filtering: names of datasets are given, all related entries in other v1-collections should be migrated with it. What other options we give (assumption: _migrate all_ (no filtering), then perhaps allow separate additional filters for other entity types (property defs, mapping tables, ...)
7. How will the migration be run 1:1 or 1:N? (relates to the next point)
7. How do we keep track of the previous sync?  
  a. For strictly 1:1, we can mark flag it in source db or keep an external log, or on target (in entity or separate collection)?
  b. For 1:N, external log or on target db?
7. Assuming to be able to run repeatedly to fill in missing data (e.g. new dataset versions are added). What about conflicts? E.g. sync on `Dataset123ABC`, versions 5; next run encounters:
  a. source: v7, target v5 => ok, sync v6+7 
  b. source v7, target v6 => ok, sync v7 (but we need to check the sync log if not out-of-sync)
  c. source v7, target v8 => abandon sync, definitely out-of-sync changes. 
8. When migration fails, how do we cleanup locks? Perhaps we should keep the migration run somewhere (a collection with TTL)

**Comment by Zejnilovic** [comment]
1. yes
2. yes
3. No. Create a second script for collection/index creation
4. Don't migrate
5. Agreed
6. Datasets + Mapping Tables finding. Migrate all is a secondary feature, not needed now.
7. 1:1
8. Tracking in DB is a very cool idea
9. Locking should stop us from conflicts.
10. We don't. Locks are forever.

**Comment by dk1844** [comment]
Some more question space:
1. when migrating, do we always migrate all entity versions or just the needed ones? E.g.
  a. Existing versions of the dataset `MySuperDs` only reference `MyAwesomeSchema` in versions `3`-`5`, but `MyAwesomeSchema` highest version is `7`. What versions of the schema do we migrate? `3`-`5`? `1`-`5`? Or all of them, so `1`-`7`?

**Comment by benedeki** [comment]
> Some more question space, @Zejnilovic, if you please:
> 
>     1. when migrating, do we always migrate all entity versions or just the needed ones? E.g.
>        a. Existing versions of the dataset `MySuperDs` only reference `MyAwesomeSchema` in versions `3`-`5`, but `MyAwesomeSchema` highest version is `7`. What versions of the schema do we migrate? `3`-`5`? `1`-`5`? Or all of them, so `1`-`7`?

All versions. Entity is either migrated (completely) and locked or not migrated at all.

**Comment by dk1844** [comment]
OK, understood. Just note, that could lead to migrating entities you would theoretically not need to migrate at all. E.g. you are migrating dataset `dsA` that has mapping CR referencing mapping table `mtA` v2. `mtA` v2 is based on schema `mtAschema`. However, this way, when migrating all versions, you also migrate `mtA` v3, which references `mtAEnhancedSchema`. So you need to migrate all versions of this schema entity, too, even though you would not need to run `dsA` at all.

Maybe this is a corner case, just let's be aware of this stretch ;)

**Comment by dk1844** [comment]
Release notes
An initial version of a python-based MongoDB migration script has been added.
