### ISSUE TITLE
Spline 0.3 doesn't write lineage file to S3

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1894]
## Describe the bug
When the output path for either _Standardization_ or _Conformace_ is an S3 storage path _SPLINE file is no created,

## To Reproduce
1. Have a dataset with _publish_ path set to S3
2. Run _Standardization_ and _Conformance_ with Spline active on the dataset
3. See that the _publish_ folder contains data, but no _SPLINE file
4. (Same if the intermediate destination after _Standardization_ is located on S3)

## Expected behavior
The _SPLINE file is present with normal content.

**Comment by dk1844** [comment]
Release notes:
Enceladus can write Spline's `_LINEAGE` file in an S3 location.
