### ISSUE TITLE
Info Version from conformed columns

### ISSUE THREAD

**Issue by AdrianOlosutean** [AbsaOSS/enceladus#1898]
## Background
Currently the Info Version  can only be taken from columns prior to conformance, which is a bit restrictive

## Feature
Add the ability to specify conformed columns as columns for `enceladus_info_version`

**Comment by benedeki** [comment]
Useful subtask of this would be to generate the expected schema after conformance phase.

**Comment by AdrianOlosutean** [comment]
Release notes
`enceladus_info_version` can now be taken from a conformed column in HyperConformance
