### ISSUE TITLE
On Import Dataset validate extra output columns of MappingTableConformanceRule

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1904]
## Background
We added `additionalColumns` to `MappingConformanceRule` but did not add validation of these fields on import

## Feature
On Import Dataset validate extra output columns of MappingTableConformanceRule

**Comment by AdrianOlosutean** [comment]
Release notes
On Import Dataset, all output columns of MappingTableConformanceRule will be validated
