### ISSUE TITLE
Add new features to Enceladus needed for data migration

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1919]
## Background
We will be migrating Enceladus (Menas) data between two location, while both will be used at the same time. This might require extra capabilities of the project to support this migration.

## Feature
Add identified features required or useful for successfully exercising and concluding the migration. Features are yet to be identified and described.

## Proposed Features
1. Locking a dataset/any Menas entity, including data model change and API
2. ???

**Comment by AdrianOlosutean** [comment]
Release notes 
Added ability to lock and unlock an entity. A locked entity will forbid any update operation
