### ISSUE TITLE
Make it possible to have mapping rule without a join condition

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#1938]
## Background
With the ability of filtering it is possible the mapping table is reduced enough, and there's no need to add a join condition.

## Feature
Make it possible to have no join condition on the Mapping Conformance Rule - support must exist both on back-end and front-end.

**Comment by dk1844** [comment]
Release notes
Mapping Conformance Rule may now exist without a join conditions, but in such a case a non-empty filter must be defined instead.
