### ISSUE TITLE
Schema doesn't update when I switch datasets

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#196]
## Describe the bug
If I have schema tab opened in Datasets view and I change the dataset opened, the schema doesn't update. Basic Info and Conformance Rules does.

## To Reproduce
1. Open Datasets and choose dataset
2. Open schema tab
3. Change the dataset to another
4. Nothing updates

## Expected behaviour
I expect the schema to update when I click between the datasets.

## Screenshots
![feb-27-2019 09-47-54](https://user-images.githubusercontent.com/17467768/53477356-d115e080-3a74-11e9-951f-de4e8339a1c2.gif)

## Desktop (please complete the following information):
- OS: macOS 10.14.3
- Browser Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by lokm01** [comment]
This seems to be irrelevant now since the tabs reset to the first one.

**Comment by Zejnilovic** [comment]
True, true. Closing.
