### ISSUE TITLE
Migration Script - Do not lock runs, attachments

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#2015]
## Background
Runs & attachments are not editable and should not be locked during migration.

## Feature
Do not lock Attachments & Runs when migrating. But keep migrated=true.

**Comment by dk1844** [comment]
> Runs are not editable and should be locked

do you menas _should **NOT** be locked_?

**Comment by Zejnilovic** [comment]
> > Runs are not editable and should be locked
> 
> do you menas _should **NOT** be locked_?

Yes. Sorry
