### ISSUE TITLE
Folding of a file tree structure leaves all the elements present

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#202]
## Describe the bug
If I go to New Dataset or Edit dataset and open up/unfold some file structure, I can not get it to close back again.

## To Reproduce
1. Open any Dataset
2. Click on edit
3. Choose some deeper place in HDFS raw data folder path
4. Try to fold the structure back using the array on the left

## Screenshots
![mar-04-2019 07-58-52](https://user-images.githubusercontent.com/17467768/53716074-f8ddbd80-3e53-11e9-907e-ed7b5a743cc7.gif)

## Desktop (please complete the following information):
- OS: macOS 10.14.3
- Browser Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by GeorgiChochov** [comment]
I think this was fixed along with #169 in PR #327. @Zejnilovic can you confirm if we can close this?

**Comment by Zejnilovic** [comment]
I confirm, fixed in #327. Thanks for spotting it!
