### ISSUE TITLE
Support multiple AD servers for authentication

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2024]
## Background
Right now Menas is able to use only AD server for authentication (`menas.auth.ad.server`).

## Feature
Enable multiple servers setup for resiliency.

## Proposed Solution
1. Go to `class MenasKerberosAuthentication`
2. Function `kerberosLdapContextSource`
3. Use the multiserver constructor for [`KerberosLdapContextSource`](https://docs.spring.io/spring-security-kerberos/docs/current/api/org/springframework/security/kerberos/client/ldap/KerberosLdapContextSource.html)
4. Some new configuration might be needed

## Open Question
Should there be a new key for multiple servers or use the original `menas.auth.ad.server` and parse it?

**Comment by dk1844** [comment]
Having looked at the code, I think no implementation is necessary. Provided the setting used like this
`menas.auth.ad.server="ldap://first.ldap.here/sameDn ldap://seconds.ldap.here/sameDn`, it should work.

**Comment by dk1844** [comment]
Having tested it, we actually use no DN in the URLs at all, the DN is supplied by `menas.auth.ldap.search.base` later. But simply using `menas.auth.ad.server=ldaps://first.ldap.here ldaps://second.ldap.here ldaps://third.ldap.here` seemed to work 😀

**Comment by dk1844** [comment]
Related documentation PRs: #2025 #2026.
