### ISSUE TITLE
Make 404 an optionally recoverable error when calling rest api endpoint

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2072]
## Background
When call from _Spark Job_ to _Menas REST API_ fails, if the error is considered recoverable another of the configured servers is tried.

## Feature
`404` is not considered recoverable. Make it configurable that `404` can be considered recoverable to try a different server.

## Bonus [Optional]
Maybe it could be done generally, that a list of error status codes can be configured, that will be considered recoverable.

**Comment by lsulak** [comment]
## Release notes
A user can specify a list of HTTP error status codes that are allowed to be retried when a REST API call yields such an HTTP error. Currently supported HTTP error status codes: 401, 403, and 404.
