### ISSUE TITLE
Buttons on Menas welcome screen are in wrong order

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2095]
## Describe the bug
The buttons on the Menas UI welcome screen are in the wrong illogical order, different from left side column.

## To Reproduce
Open Menas UI
1. Go to '.Home screen'
2. See the buttons

## Expected behavior
Order the buttons in the similar order as the left side column:
* Runs
* Schemas
* Datasets
* Mapping Tables
* Dataset Properties

(or if you find even more logical order fix both)

## Screenshots
![Menas.png](https://images.zenhubusercontent.com/5bffd61ae4230d2799962db8/6b2655e9-55e8-4dc5-94b2-d444f5226631)

**Comment by dk1844** [comment]
Release notes
Menas UI: Lading page buttons order has been changed to conform the order of items in the left-side menu.
