### ISSUE TITLE
Outdated `spark-jobs` configuration referncing Menas

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2105]
## Describe the bug
Outdated `spark-jobs` configuration referencing Menas

## To Reproduce
Check he `reference.conf` in _Spark-jobs_ module

## Expected behavior
Configuration should not use Menas in the configuration keys.
Fix the default `reference.conf` not to use misleading values with Menas

## Suggested fixes
* Change the keys starting with `menas.rest.` to `enceladus.rest.`
* Change the demo values to user `rest-api` rather then `menas`
* Fix the examples configurations
* Fix the documentation (both `README.md` and `github.io` ones)

**Comment by jakipatryk** [comment]
Release notes
spark-jobs: Configuration keys starting with `menas.rest` were changed to `enceladus.rest`.
