### ISSUE TITLE
On failed calling Rest-API wait for random moment

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2121]
## Background
When a _Rest-API_ calls fails from _SparkJobs_ it is retried immediately, possibly creating an ingestion on the Rest endpoint.

## Feature
In case of a failure & retry on Rest API call add a random length ~2 seconds sleep.

**Comment by jakipatryk** [comment]
Release notes
dao: A random (quadratically + linearly randomized) wait has been added between retries of the same URL and between switching URLs on calling the REST API
