### ISSUE TITLE
Integration test failing with MongoDB 4.4

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/enceladus#2125]
## Describe the bug
The method `db.collection.listIndexes()` no longer returns the namespace `ns` field in the index specification documents.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Run integration test with MongoDB 4.4

Bug description is valid for Integration tests:
- [Test index adding/removal](https://github.com/AbsaOSS/enceladus/blob/develop/migrations/src/test/scala/za/co/absa/enceladus/migrations/framework/integration/MongoDbIntegrationSuite.scala#L83)
- [Test unique index adding/removal](https://github.com/AbsaOSS/enceladus/blob/develop/migrations/src/test/scala/za/co/absa/enceladus/migrations/framework/integration/MongoDbIntegrationSuite.scala#L109)
- [Test dropping an index with the wrong sort order](https://github.com/AbsaOSS/enceladus/blob/develop/migrations/src/test/scala/za/co/absa/enceladus/migrations/framework/integration/MongoDbIntegrationSuite.scala#L136)
- [Test index copying on clone](https://github.com/AbsaOSS/enceladus/blob/develop/migrations/src/test/scala/za/co/absa/enceladus/migrations/framework/integration/MongoDbIntegrationSuite.scala#L171)
- [Test unique index copying on clone](https://github.com/AbsaOSS/enceladus/blob/develop/migrations/src/test/scala/za/co/absa/enceladus/migrations/framework/integration/MongoDbIntegrationSuite.scala#L210)

## Expected behavior
Tests will pass.

## Additional context
Link to MongoDB [change documentation](https://www.mongodb.com/docs/v5.3/release-notes/4.4-compatibility/#general-changes) with described behavior change.

**Comment by dk1844** [comment]
This is a definitely valid find attempting to use MongoDB 4.4+ with the current `develop`.
The current codebase is written with MongoDB 4.0 in mind.

Considering that some of our on-premise environments are MongoDB-4.0-based, how do we want to proceed?

Maybe would make sense to target more recent Mongo (maybe even v5 or v6) for the future branches (`develop-spark-3` already featuring Scala 2.12, Spark3, and Hadoop3)?

@benedeki @Zejnilovic
