### ISSUE TITLE
Update to newest verson of Cobrix

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2139]
## Background
[Cobrix](https://github.com/AbsaOSS/cobrix) is in higher version than the used one.

## Feature
Update to the newest version of [Cobrix](https://github.com/AbsaOSS/cobrix) available. There seem to be some interface changes.

**Comment by jakipatryk** [comment]
Release notes
Cobrix has been upgraded to version 2.6.0
