### ISSUE TITLE
Remove Hardcoded Spline, use codeles init

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#2152]
## Background
To align with the planned practices, we should remove hardcoded dependency on other projects, even though they come from our own back yard. This allows us to release more often and independently.

Spline has a feature called codeless init. This is a perfect feature for this.

## Feature
- [ ] Remove Hardcoded spline from spark-jobs
- [ ] Replace Menas' Spline tab with a link
  - [ ] Link can be a directly to the lineage from specific run
- [ ] Add Spline codeless initialization in shell scripts

**Comment by wajda** [comment]
any update on this please? Is there any ETA for UAT?

**Comment by benedeki** [comment]
> any update on this please? Is there any ETA for UAT?

After Enceladus 3.0.0 will have been released (which this will be a sure part of it) we will discuss with relevant people when they allow it to go to the env.
Actually this is probably the last noteworthy change to be added to the release.

**Comment by Zejnilovic** [comment]
Release Notes:
Remove HardCoded spline. Add options to bash scripts to run spline codeless.
