### ISSUE TITLE
Accept Dataset without conformance rules

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#2162]
## Background
When Dataset definition is submitted to Rest-API, it fails if list of conformance rules is not defined.
For easier operation (and eventual phase out of Conformance), it would be natural that if the Conformance rules are not provided it's considered and empty list.

## Feature
If `Dataset` (from `za.co.absa.enceladus.model`) has not defined property `conformance` during deserialization, consider it an empty list. 

## Proposed Solution
Solution Ideas:
1. Setting the property's default value to be `List.empty` should suffice
2. Verify then with Rest-APIs that insert a new Dataset or edit an existing one.

**Comment by TebaleloS** [comment]
Release notes
Dataset conformance is now optional, if it is not defined it assigns an empty list as a default value.
