### ISSUE TITLE
release_deploy.cmd fails due to javadoc generation issue

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/enceladus#2182]
## Describe the bug
When trying to release v 3.0.0 with `release_deploy.cmd`, the following problem appeared
```
[INFO] --- scala-maven-plugin:4.4.0:doc-jar (default-cli) @ dao ---
<my path>\enceladus\dao\src\main\scala\za\co\absa\enceladus\dao\rest\RestClient.scala:86: warning: discarding unmoored doc comment
    /**
    ^
error: No warnings can be incurred under -Xfatal-warnings.
...
```
This problem has not been revealed before while building the project otherwise.

## To Reproduce
Steps to reproduce the behavior OR commands run:
```shell
mvn install
mvn net.alchim31.maven:scala-maven-plugin:4.4.0:doc-jar
```

**Comment by benedeki** [comment]
With fixing that, let's add the verification step to GitHub actions.
