### ISSUE TITLE
s3a Wrapper script null-value behaviour 

### ISSUE THREAD

**Issue by MatloaItumeleng** [AbsaOSS/enceladus#2210]
## Describe the bug
S3a wrapper script does not work with `--null-value` when passed as `--null-value '        '`

## To Reproduce
Steps /commands  to run to reproduce the behavior:
```sh
/<Wrapper_script_path>/s3a_wrapper.sh /<helper_script_path>/run_standardization.sh --deploy-mode cluster --dataset-name Custom_datasetName --menas-auth-keytab /<user_cred_file_path>/user_authFile.krb --dataset-version 1 --report-date 2024-02-07 --report-version 1 --raw-format csv --charset cp1252 --header false --delimiter U+00A6 --null-value '        '
```
## Expected behavior
s3a_wrapper script should not throw a warning for the given inputs parameters similarly when helper script is used individually as seen on screenshot provided below

## Screenshots
![image](https://github.com/AbsaOSS/enceladus/assets/77967975/03c0d96c-e1f8-4d12-bcf9-d153d281ad9a)
compared against warning when using null-value '       ' on s3a wrapper script
![image](https://github.com/AbsaOSS/enceladus/assets/77967975/39a54d99-2305-4a60-8d0a-5b76de548ab1)

## Desktop (please complete the following information):
 - OS: Windows
 - Browser chrome
 - Version 121.0.6167.88

**Comment by dk1844** [comment]
I will let @MatloaItumeleng know about this fix
