### ISSUE TITLE
Dependencies on other objects lingers even after deletion

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#222]
## Describe the bug
If I have a `datasetY` that has is using `schemaX`. I can delete the `datasetY` and I will still be getting an error, that I am not allowed to delete the `schemaX` because there is a dependency on `datasetY`

## To Reproduce
1. Create schemaX
2. Create datasetY with schemaX
3. Delete datasetY
4. Try deleting schemaX

## Expected behaviour
If I delete the dependency I expect to be able to delete the object.

**Comment by lokm01** [comment]
Can you retest on develop? I can't replicate.

**Comment by Zejnilovic** [comment]
Presumably already fixed. Closing
