### ISSUE TITLE
Update verision of scalatest and scalatest-maven-plugin 

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#225]
## Background
Update verision of scalatest and scalatest-maven-plugin in pom. Speed up the build since the updated versions have performance optimalizations.

**Comment by Praveen456B** [comment]
Still getting an issue for downloading scalatest after updating the version

**Comment by lokm01** [comment]
> Still getting an issue for downloading scalatest after updating the version

Can you share your build errors? Are you behind a proxy?

**Comment by Praveen456B** [comment]
PC accesses the Web through a proxy server only..

See the below error:
Downloading: https://repo.maven.apache.org/maven2/org/scalatest/scalatest-maven-
plugin/2.0.0/scalatest-maven-plugin-2.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.260 s
[INFO] Finished at: 2019-06-21T14:58:38+05:30
[INFO] Final Memory: 10M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.scalatest:scalatest-maven-plugin:2.0.0 or one of its dependen
cies could not be resolved: Failed to read artifact descriptor for org.scalatest
:scalatest-maven-plugin:jar:2.0.0: Could not transfer artifact org.scalatest:sca
latest-maven-plugin:pom:2.0.0 from/to central (https://repo.maven.apache.org/mav
en2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.184.21
5] failed: Connection timed out: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResoluti
onException

**Comment by Zejnilovic** [comment]
You have three options:
1. Downgrade locally the scalatest dependencies back to the original numbers by modifying the pom.xml
2. Download the dependencies by hand and put them into the maven repository folder on the machine.
3. Update your proxy settings.

**Comment by lokm01** [comment]
You must be behind some sort of a corporate firewall.

See https://stackoverflow.com/questions/1251192/how-do-i-use-maven-through-a-proxy

**Comment by Praveen456B** [comment]
Thanks a lot to both Zejnilovic and  lokm01 for your help, i did mistake in my proxy host setup, now i did changes and I can able to download the jars..thanks:)
