### ISSUE TITLE
hh vs. HH formatter in date&time conversion

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#230]
## Describe the bug
When converting `String` to `Timestamp` in _Spark_ only **HH** is supported to mark the number of hours. On the other hand _Java_'s `SimpleDateFormat` can recognize **hh** in this context too.
By transitivity Enceladus timestamp validation (`DateTimeValidator`) will approve pattern with **hh**,  while the Standardization will fail (create NULL value in the column).

## Expected behavior
The validator should reliably evaluate which patterns will be working correctly with Spark/Enceladus Standardization.

**Comment by yruslan** [comment]
What Spark uses for datetime? Is it `org.joda.time.DateTime`, `java.time`or `java.time.ZonedDateTime`?
Maybe we could use the same for our pattern requirements and validation so it will match?

**Comment by benedeki** [comment]
Turns out *hh* and *HH* are both supported the same way. It was just a coincidence, and furhter investigation revealed the reason for the failure. *hh* is 1 based, therefore it fails on 00:20:31.
In any case the linked PR beefs up the validation and fixes other problems.
