### ISSUE TITLE
Navigation button disappears after re-login

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#246]
## Describe the bug
If I get logged off with open Navigation, then after I login in again I don't see the button. 

If I "reload" it solves the problem in 99% of times and "reload with override cache" solves it the rest of the times.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Open Navigation
2. Log out
3. Log back in

## Screenshots
![Mar-19-2019 08-10-44](https://user-images.githubusercontent.com/17467768/54587031-295e5380-4a1f-11e9-8eee-7c361e176dae.gif)

## Desktop (please complete the following information):
- OS: macOS 10.14.3
- Browser Version 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)

**Comment by GeorgiChochov** [comment]
Fixed along with #195 in PR #277
