### ISSUE TITLE
Unable to open new Dataset/Mapping Table dialog when no Schema is available

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#253]
## Describe the bug
When there is no Schema present in the database, trying to create a new Dataset or Mapping Table (because they depend on Schemas being available), the UI is unresponsive, i.e. the new entity dialog does not open.

## To Reproduce
1. Have an empty schemas collection in Mongo
2. Log in to Menas
3. Go to Datasets/Mapping Tables
4. Press on New Dataset/Mapping Table
5. UI is unresponsive (error gets logged in console)

## Expected behaviour
An error should pop up, notifying the user that there are not Schemas available for the new entity to be created.

## Screenshots
![image](https://user-images.githubusercontent.com/20905867/54606769-021e7b00-4a4d-11e9-9c43-a6b05a532ef1.png)

## Desktop (please complete the following information):
 - OS: MacOS
 - Browser: chrome

**Comment by Zejnilovic** [comment]
This is not an issue anymore since we use FlexBox with ListItem in `schemaSelector.fragment.xml`. 

![image](https://user-images.githubusercontent.com/17467768/64152214-70ed6600-ce2c-11e9-912d-be48bc88a60d.png)
