### ISSUE TITLE
Materialize application.conf templates rather than failing the build

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#256]
Let's replace the enforcer plugin, which fails the build if the application.conf is missing from the main resources.

Rather let's materialize the template on the first build, which will provide reasonable defaults without necessary providing custom configs while preserving existing files.

This means that people should be able to clone and build the project (incl tests) out of the box.

**Comment by Zejnilovic** [comment]
This will also mean rewriting the templates, so they work out of the box.
