### ISSUE TITLE
Upgrade to Spark 2.4.3

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#285]

**Comment by lokm01** [comment]
@yruslan some of the Deep Transformation tests fail on 2.4.1

**Comment by yruslan** [comment]
This is a very interesting issue. 23 deep array transformation tests fails after upgrade to 2.4.1. And 12 tests in spark-hofs 0.1.0 fails as well. Investigating...

**Comment by yruslan** [comment]
Opened an issue for `spark-hofs` (https://github.com/AbsaOSS/spark-hofs/issues/1). Working on it there...
