### ISSUE TITLE
Remove print lines from UnitTests

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#291]
## Describe the bug
Remove standard print lines from unit tests. If the print line is needed make it into a `log.debug`.
This should improve compilation time as well.

**Comment by Zejnilovic** [comment]
@benedeki I think you fixed this already. Did you not?

**Comment by benedeki** [comment]
Yes. I believe I addressed all occurrences - both of `print` and `dataframe.show`.
Closing the ticket, feel free to reopen in case you find it premature.

**Comment by benedeki** [comment]
For the record it was done as part of several of #717 tickets
