### ISSUE TITLE
Prepare env for E2E tests

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#296]
We currently possess the E2ERunner ( #244 ) which runs standardization and conformance and evaluates the outputs.

~~Now we need a rest setup that will call the Menas back-end and create a schema, mapping tables and dataset queries. This would then be full E2E tests.~~

EDIT1:  We redefined our E2E setup and it will handle one E2E process at the time, not the whole usage at once. This is mainly because even for users these are divided tasks and functionalities. The environment from the point of tools and apps has been fully prepared, the only thing missing is to **prepare the final data**.

**Comment by Zejnilovic** [comment]
We are switching from REST. Rest tests are a standalone thing that is going to be tested e2e through different means. 

This now consists of data structure, versioning and means of running.

**Comment by GeorgiChochov** [comment]
What's up with this task? Do we keep it, redefine the scope or close?

**Comment by Zejnilovic** [comment]
> What's up with this task? Do we keep it, redefine the scope or close?

We are a bit behind the previous plan, but @hamc17 and I are still trying to do something about it. This is just lagging behind because of all the changes on AWS and our own time unavailability and other priorities.

**Comment by GeorgiChochov** [comment]
@Zejnilovic Could you update the description of this task to reflect what it actually involves now? Since it's scope has changed, it no longer fits the actual work that needs to be done on it.

**Comment by hamc17** [comment]
Runner job has been created, manually running has worked & job retrieval of required artifacts is done.
S3 retrieval for different datasets/dumps will be done soon, then full automated run will be possible.
The end user can then select the desired artifacts & datasets/dumps and run the tests.
