### ISSUE TITLE
Mongo DB initialization on new deployment

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#297]
Currently, on new a deployment Menas fails if the evolution collection doesn't contain the initial evolution.

It'd be great if the database could be initialized automatically and properly in case config points to an empty mongo db.

**Comment by GeorgiChochov** [comment]
It does initialize, create the database, the evolutions collection, populates it and runs fine when pointing to an empty/non-existent db... as long as you have the the `mongodump/mongorestore` executables available. That's the only current requirement for evolutions to run. I have recreated the basic `mongodump/mongorestore` funcitonality in a separate project with the scala driver, so we don't have to rely on these executables. It is completely interoperable with them, but is just hastily thrown together library still not handling all the options the mongo-tools provide. When I get a chance I'll get back to it and finish it, then we can use it here.

**Comment by lokm01** [comment]
Ok, tested this with:
- mongodump available on PATH
- local & remote hadoop
    - sadly this is broken for HDP sandbox by default as it's not exposing the datanodes through the NAT

Let's close this
