### ISSUE TITLE
Keep the unified menu/master pane open by default

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#299]
I think from UX perspective it'd be cleaner if the unified menu was open by default.

It's quite confusing when the first run opens and it's not immediately obvious where the user is. This might be easier with the menu open. I believe there's a choice to close it by default for smaller screens, this may be best.

**Comment by Zejnilovic** [comment]
This is a duplicate of -> Navigation should be always visible #281

**Comment by lokm01** [comment]
Ok, closing this one then.
