### ISSUE TITLE
Include breadcrumbs component on all entity pages

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#300]
Can we include breadcrumbs navigation component somewhere?

I guess it would help users realise where they are in terms of navigation much easier.

**Comment by Zejnilovic** [comment]
We have four "main views" which are always specific data, each of them with only one more level of depth (basic info, schema, etc.). If the #281 gets implemented I think there is no reason to show breadcrumbs.

Breadcrumbs would make more sense if we have the main view of all our models, then the view of the list of data of the model and then specific data. Example below:
![image](https://user-images.githubusercontent.com/17467768/55645244-6032b880-57d8-11e9-8852-1ba92b4e5b34.png)
![image](https://user-images.githubusercontent.com/17467768/55645250-632da900-57d8-11e9-8088-91a3266636f6.png)
![image](https://user-images.githubusercontent.com/17467768/55645264-688af380-57d8-11e9-8d49-a4249458c2fd.png)

But I can not imagine what to have there in our case. We Choose in the navigation on the left and that's it, you don't have anywhere to go back to in terms of levels. And doing this for panels would make a big messy loop.

**Comment by GeorgiChochov** [comment]
I agree with @Zejnilovic, this doesn't make sense in our setup.
