### ISSUE TITLE
Conformance fails when output columns are similar

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#305]
## Describe the bug
When running an end-to-end test on a sample data Conformance Job crashes when output columns of mapping conformance rules are inside an array and their names differ only by a number appended to it. In this case "legs.leg.ConformedCurrency" and "legs.leg.ConformedCurrency2" cause the issue. But if the output column of the second mapping rule is renamed, Conformance Job does not fail. For instance, for these output column names Conformance Job works fine: "legs.leg.ConformedCurrency", "legs.leg.NewConformedCurrency". 
Stack trace:
```
Exception in thread "main" org.apache.spark.sql.AnalysisException: No such struct field ConformedCurrency2 in ABSATraded, CurrencyCode, CurrencyName, MajorIndicator, PermissibleDailyVolatility;
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.findField(complexTypeExtractors.scala:85)
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:53)
...
```
( the full stack trace is attached - [full-stack-trace.txt](https://github.com/AbsaOSS/enceladus/files/3054396/full-stack-trace.txt) )

Mapping rules definitions that cause the issue:
```json
        {
            "_t" : "MappingConformanceRule",
            "order" : 5,
            "controlCheckpoint" : true,
            "mappingTable" : "CurrencyMappingTable",
            "mappingTableVersion" : 1,
            "attributeMappings" : {
                "SourceSystem^SourceSystem" : "ConformedSourceSystem.SourceSystem",
                "InputValue" : "legs.leg.currencyName"
            },
            "targetAttribute" : "Currency",
            "outputColumn" : "legs.leg.ConformedCurrency",
            "isNullSafe" : true
        }, 
        {
            "_t" : "MappingConformanceRule",
            "order" : 6,
            "controlCheckpoint" : true,
            "mappingTable" : "CurrencyMappingTable",
            "mappingTableVersion" : 1,
            "attributeMappings" : {
                "SourceSystem^SourceSystem" : "ConformedSourceSystem.SourceSystem",
                "InputValue" : "legs.leg.currencyName"
            },
            "targetAttribute" : "Currency",
            "outputColumn" : "legs.leg.ConformedCurrency2",
            "isNullSafe" : true
        }, 
```

## To Reproduce
1. Setup a dataset with mapping rules as above
2. Run a Conformance Job

## Expected behaviour
Conformance Job should not crash if output column names are inside an array and when several different mapping rules have similar output column names.

## Additional context
The new experimental conformance rule interpreter does not have this issue. So it might be something related to handling nested arrays.

**Comment by GeorgiChochov** [comment]
Closing as this has already been fixed.
