### ISSUE TITLE
Model migration framework

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#311]
## Background
We need a way to safely evolve our data models and migrate from the old to the new Menas. Currently, there is the evolutions module which is designed for in-place data evolutions. A better idea was proposed by @yruslan which would allow a graceful transition period from old to new Menas.

## Feature
In this implementation the collections would be copied and versioned. This allows us to rollback without restoring from an old dump (no downtime), or even run multiple versions of Menas with the same database.

## Requirements
1. Full database migration is the focus. Migration from the old Menas to the pre-1.0 release is the priority.
2. The new database should be protected from old Menas/Enceladus writing data in an old schema.
3. Migration can be incremental, e.g. from version 1 to version 2, then 2->3, then 3->4. No need to jump from 1->4.
4. A rollback to the old data should be possible incase something goes wrong.
5. Migration can be done when the services are down.

# Implementation ideas
1. Add a version postfix to collection names so services write to the specific collection version only. E.g. instead of `dataset`, `schema`, ... we will have `dataset_v1`, `schema_v1`, ...
2. The version of the collections to use can be hard-coded as a constant.
This will protect data against writes done by older versions of services.
3. Store all versions of models in versioned packages in `migrations` module. E.g, the package structure will be something like this:
```
migrations
    +--- models
           +--- v1
           |     + Dataset
           |     + Schema
           |     + MappingTable
           |       ...other case classes ...
           +--- v2
           |     + Dataset
           |     + Schema
           |     + MappingTable
           |       ...other case classes ...
           ...other model versions ...

```
4. Since currently the model is quite heavyweight, no need to copy all of its implementation details, just a serialisable equivalent.
5. The migration itself is done per collection basis. So only collection that changes should be present in the packages structure. Nevertheless, even if a schema of a collection didn't change the records should still be copied to the collection with a new name.
6. Migration can consist of 2 components. One is, for example, `record-processor`, the other is `transformer`.
    - The record processor will fetch all documents from a collection as a JSON, pass it to the transformer, which will return another JSON. The record processor will then write each transformed document.
    - The transformer will take a JSON, deserialise it into a new model, copy objects from the old model to the objects of the new one, serialize it and return the new JSON.
    - One type of transformer can be an "identity" transformer which returns the same JSON that was passed to it. This will be used for collections that do not require migrations when transitioning from a particular version to the next one.
6. In this case no rollback is required. A revert to the old version can be done by simply stopping the new version of Menas and starting the old one.

**Comment by yruslan** [comment]
Thanks @Zejnilovic for bringing up that db migrations should convert control metrics to strings for all `Run` objects.
