### ISSUE TITLE
Improve Mapping Conformance Rule

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#341]
## Description
Let users choose the columns for join conditions from a schema picker. This picker will need to be aware of the dataset's schema and mapping table's schema.

**Comment by GeorgiChochov** [comment]
When a join condition dialog is reopened to edit the join, the fields are preselected but that preselection is not reflected in the model. Pressing `accept` without changes results in no fields selected for the join condition.
