### ISSUE TITLE
Search, Sort and Filter entities

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#35]
Users should be able to search filter and sort their schemas/mapping tables/datasets in the Menas UI for easier navigation.

**Comment by Zejnilovic** [comment]
Is this Epic worth of closing? It has every Issue completed.

**Comment by GeorgiChochov** [comment]
Yeah, let's close it. I wanted to add criteria-based filtering as well but didn't create the tasks for it. They don't need to be in an epic.
