### ISSUE TITLE
Mapping Table Default value edit should show what column is selected

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#368]
## Background
When updating a Mapping Table Default Value, I expect to see in the schema selector what is currently selected (it having a blue dot next to it)

Even better if it can be centred to that field on open. This, I think was already done for conformance rules by @jozefbakus in #197

## Example
On open I see 
![image](https://user-images.githubusercontent.com/17467768/57192216-4e0a7e00-6f2e-11e9-8200-ed1ef13339ea.png)
Where I had to click `strings` myself to open the dropdown and `all_random` is missing the blue dot next to it.

**Comment by Zejnilovic** [comment]
@GeorgiChochov  is this a duplicate to #364 ?

**Comment by GeorgiChochov** [comment]
> @GeorgiChochov is this a duplicate to #364 ?

Yes, please label it as such and close it.

**Comment by Zejnilovic** [comment]
> > @GeorgiChochov is this a duplicate to #364 ?
> 
> Yes, please label it as such and close it.

Sorry, took me a while to sort it out. I blame Sunday!

**Comment by GeorgiChochov** [comment]
> > > @GeorgiChochov is this a duplicate to #364 ?
> > 
> > 
> > Yes, please label it as such and close it.
> 
> Sorry, took me a while to sort it out. I blame Sunday!

Lol, forgot it's Sunday.
