### ISSUE TITLE
Conformance takes too long after adding 5 simple rules

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#413]
## Describe the bug
I added 8 simple conformance rules. Some `UpperCaseRule`, some `NegationRule` and one `LiteralRule`. Test data can be found at the [bottom](#bottom). And the whole conformance job hangs. I have not waited for the timeout I always killed it after approximately 4 minutes.

7 simple rules make the time go from 12 seconds to 2 minutes and 20 seconds

### Data Preparation
```bash
# GitHub doesnt allow json and non formats, so we need to switch them back.
mv dataset_definition.txt dataset_definition.json 
mv schema_definition.txt schema_definition.json
mv testData.txt testData.json
mv _INFO.txt _INFO

# Import data to mongo. Add --host, --port or --authenticationDatabase
# if applicable
mongoimport --db menas --collection dataset --file dataset_definition.json
mongoimport --db menas --collection schema --file schema_definition.json

# Create HDFS file structure that the imported dataset reckognizes
hdfs dfs -mkdir -p /toStandardize/FirstJsonData/2019/02/25/v1
hdfs dfs -mkdir -p /publish/FirstJsonData
hdfs dfs -put _INFO testData.json /toStandardize/FirstJsonData/2019/02/25/v1
```

### Standartization
```bash
spark-submit \
--num-executors 2 \
--executor-memory 2G \
 --deploy-mode client \
--master local \
--class za.co.absa.enceladus.standardization.StandardizationJob \
--conf 'spark.driver.extraJavaOptions=-Dmenas.rest.uri=http://localhost:8080/menas/api -Dspline.mongodb.name=spline -Dhdp.version=2.7.5' \
/Users/absz189/Development/enceladus/standardization/target/enceladus-standardization-0.99.0-SNAPSHOT.jar \
--menas-credentials-file ~/.ssh/menas-credential.properties \
--dataset-name FirstTestData \
--dataset-version 73 \
--report-date 2019-02-25 \
--report-version 1 \
--raw-format json
```

### Conformance
```bash
spark-submit \
--num-executors 4 \
--executor-memory 4g \
--master local \
--driver-cores 4 \
--driver-memory 4G \
--conf "spark.driver.extraJavaOptions=-Dmenas.rest.uri=http://localhost:8080/menas/api -Dconformance.mappingtable.pattern=reportDate={0}-{1}-{2} -Dspline.mongodb.name='spline_jedi' " \
--class za.co.absa.enceladus.conformance.DynamicConformanceJob \
/Users/absz189/Development/enceladus/conformance/target/enceladus-conformance-0.99.0-SNAPSHOT.jar \
--menas-credentials-file ~/.ssh/menas-credential.properties \
--dataset-name FirstTestData \
--dataset-version 73 \
--report-date 2019-02-25 \
--report-version 1 \
```

## Desktop (please complete the following information):
 - Spark 2.4.3
 - Scala 2.11.12
 - Hadoop 2.7.5

## <a name="bottom" /> Additional context
**!!** Everything has text format but are original files. GitHub doesn't support json and others.
Info file - [_INFO.txt](https://github.com/AbsaOSS/enceladus/files/3206527/_INFO.txt)
Mongo dataset export - [dataset_definition.txt](https://github.com/AbsaOSS/enceladus/files/3206528/dataset_definition.txt)
Mongo schema export - [schema_definition.txt](https://github.com/AbsaOSS/enceladus/files/3206529/schema_definition.txt)
Test data - [testData.txt](https://github.com/AbsaOSS/enceladus/files/3206530/testData.txt)

**Comment by Zejnilovic** [comment]
The freeze happens even when
- I use --experimental-mapping-rule
- I have 4 upper case rules, then 1 mapping rule, then 4 negation rules

**Comment by Zejnilovic** [comment]
@yruslan  logged an active issue on spark's jira [SPARK-28016](https://issues.apache.org/jira/browse/SPARK-28016)

**Comment by yruslan** [comment]
The corresponding Spark issue is raised: [SPARK-28090](https://issues.apache.org/jira/browse/SPARK-28090).

Catalyst optimizer hangs when there are many projections to process. One of the traversal algorithms seems to be non-linear, so after certain number of projections elapsed time tends to grow very fast.

As workaround an opeartion can be used between projections so the the number of projections to optmize is never too big. That operation should act as a barrier for Catalyst optimizer. 

It seems that `.join()` can be used as such a barrier. For this implementation a cross join is used against a table of one column and one row with a subsequent drop of the added column. This results in an identity operation which does not require shuffling.
