### ISSUE TITLE
Support for long values from aggregation controlTypes from atum in Menas Runs View

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#415]
## Describe the bug
Menas doesn't properly display long controllType values of aggregation functions. It shows just `Object object` for those. Because they may no longer be simple numbers but represented as a struct like `"controlValue":{"$numberLong":"11111111111111"}`. This is not the rule. They still may be presented as simple integers. We need to take into account both.

| Type                           | Description                                           |
| ------------------------------ |:----------------------------------------------------- |
| controlType.aggregatedTotal	 | Calculates SUM() of the specified column              |
| controlType.absAggregatedTotal | Calculates SUM(ABS()) of the specified column         |

## Expected behaviour
Display calculated numbers from the struct and not the whole struct.

## Screenshots
![WhatsApp Image 2019-05-24 at 11 55 07](https://user-images.githubusercontent.com/17467768/58326774-18223080-7e2e-11e9-9e28-4618908f2142.jpeg)

**Comment by yruslan** [comment]
Not closing this one since need to double check the new behaviour of Enceladus is reflected properly in the UI. For this need to use new versions of Spark jobs.
