### ISSUE TITLE
DropConformanceRule produces no error/warning if it doesn't find the path

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#427]
## Describe the bug
Whatever path is written to drop conformance rule and it is not found, it is not logged in `errCol` nor a warning is produced. One of these should be there. 

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Create a drop conformance rule with non-existent path
2. Run Conformance

## Expected behaviour
I expect a warning in the STDOUT. Maybe even kill the whole conformance job.

## Additional context
I do understand that Menas will have a schema picker, but I still think we should have this covered. For the possibilities of someone getting data in through other means then a creation on Menas or someone using old data.

**Comment by GeorgiChochov** [comment]
No longer reproducible when specifying the column via Menas UI. Should be addressed just in case the rule is used programmatically.

**Comment by Zejnilovic** [comment]
Drop rule checks for the presence of column, if a column isn't present logs a warning
