### ISSUE TITLE
Add additional metadata for datasets

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#43]
Allow users to capture the following information for dataset level definition:
* Business Description
* Frequency

Frequency definitely could feed into our discussion for integration with Oozie and schedulers

Currently we recommend user populate as additionalInfo metadata in INFO file, which should live in Dataset definition rather than "run" metadata (INFO file)

**Comment by GeorgiChochov** [comment]
@lokm01 I have a feeling this is a non-issue anymore. Can we close it?

**Comment by lokm01** [comment]
Yeah let's close until we have more specific ideas...
