### ISSUE TITLE
Conformance handles incorrectly special characters

### ISSUE THREAD

**Issue by asheem** [AbsaOSS/enceladus#435]
## Describe the bug
A source file data has a special character value in one of the fields. After conformance, special characters are getting transformed. As suggested we have made changes in spark submit code, but still facing the same data character issue.

## Expected behaviour
Special characters not confirmed.

**Comment by Zejnilovic** [comment]
If I understand correctly it still works for me.

_All data except my name are generated randomly from a database of names_
![image](https://user-images.githubusercontent.com/17467768/58579296-033d0700-824b-11e9-8b34-70e704a7f221.png)

_All data except my name are generated randomly from a database of names_
![image](https://user-images.githubusercontent.com/17467768/58579662-d9d0ab00-824b-11e9-84cb-e5686aa67e73.png)

 **Please provide more information:**
- the charset being used and/or what are the special characters
- spark-submit job with all sensitive data removed which are dataset name and version, report date and version. Paths on the machine should be minified or just switched by a placeholder.

**Comment by GeorgiChochov** [comment]
@asheem @aaishaosman Can either of you elaborate on this? Or should we consider this resolved?

**Comment by GeorgiChochov** [comment]
I've been told this has been resolved on the user's side.
