### ISSUE TITLE
Menas limits the number of schemas to display

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#443]
## Describe the bug
When there are many schemas in the database (more than 100, determined by Saša), the list of schemas on the right side of the screen does not display all of them.

## To Reproduce
1. Create a database containing more that 100 schemas.
2. Open Menas
3. Select Schema tab
4. Some the schemas will be missing in the list.

**Comment by lokm01** [comment]
There might be item limits on private models.

**Comment by Zejnilovic** [comment]
Script to help with simulation.

```bash
for run in {1..100}
do
  echo $run
  mongo localhost:27017/menas --eval "var document = {'name' : 'TooManySchemas${run}', 'version' : 0}; db.schema.insert(document);"
done
```

**Comment by GeorgiChochov** [comment]
This applies to all `sap.m.Tree`s and `sap.m.List`s, which includes the side-menu for all entities (`List`) and and the schema field selectors (`Tree`) for conformance rules/default values.
