### ISSUE TITLE
Add control features (on/off/etc) to dataset schedule

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#446]
Currently it's impossible to disable an active schedule from Menas.

**Comment by Zejnilovic** [comment]
Be able  (from UI) to
- activate a schedule
- disable schedule (kill oozie coordinator job)
- pause schedule

**Comment by lokm01** [comment]
Ok will implemented:
- pause & resume
- run now

Kill & re-submit we may need to think about as these would produce a new DS version.
