### ISSUE TITLE
Add '--report-date' and '--report-version' to Run documents in MongoDB

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#463]
## Background
1) Monitoring currently relies on informationDate and version (run->controlMeasure->metadata->informationDate/version) in documents of the run collection. These data are derived from _INFO files provided by users. The values may have arbitrary formats and errors. A more consistent way is needed.
2) Timestamps are currently stored as strings, as a result, monitoring queries require casting [dateFromString](https://docs.mongodb.com/manual/reference/operator/aggregation/dateFromString/). Storing timestamps in [ISODate](https://docs.mongodb.com/manual/core/shell-types/) format will improve performance. 

## Feature
Add the following attributes to the documents in the run mongodb collection:
a) **reportDate** :  matching the --report-date argument of enceladus job, the corresponding part of HDFS path, and enceladus_info_date= in splineRef. The format should be ISODate.  
b) **reportVersion** : matching the --report-version argument of enceladus job, the corresponding part of HDFS path, andenceladus_info_version= in splineRef. The format should be integer.  

## Example [Optional]
"reportDate" : ISODate("2019-05-23T00:00:00.000Z")
"reportVersion" : 1

**Comment by yruslan** [comment]
Also, raw_record_count, std_record_count, conform_record_count.
