### ISSUE TITLE
Add raw_records_total to Run documents in MongoDB

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#464]
## Background
In order to get the initial number of records, monitoring relies on control values (controlType.Count)  for "Source" or "Raw" checkpoints. However, neither this control type nor the checkpoints itself are mandatory. A more reliable data is needed.

## Feature
Add raw_records_total to Run documents in MongoDB

## Example [Optional]
"raw_records_total" : 100500

**Comment by Zejnilovic** [comment]
Thing is, the control type `recordCount` does not have to be present even in standardization and conformance.

Can we read what control Type is used and show data according to it?

**Comment by DzMakatun** [comment]
#590

**Comment by yruslan** [comment]
This is already implemented as a part of #463 with the above PR.
