### ISSUE TITLE
Conformance and standardisation share too much code/logic

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#483]
## Description
Standardization and conformance share too much code and logic. These could be extracted to some general methods and/or classes. This would also prompt clean up.

Now, when we want to change something we have to duplicate our code.

**Comment by Zejnilovic** [comment]
@yruslan do you think this was solved by #1149? Or was that mostly combination of the two and deduplication would come later?

**Comment by benedeki** [comment]
IMHO not by far. I actually think this should be turned into an Epic.
The merge was just putting the two module into one. Not mch shared code extraction has been done so far.
And then there is the whole Utils module.

**Comment by yruslan** [comment]
Yeah, there is still a lot of duplicate code around Standardization and Conformance main functions that we can combine.

**Comment by AdrianOlosutean** [comment]
Can this be closed?
