### ISSUE TITLE
Go over scalastyle config

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#484]
Let's go over the scalastyle config item by item and figure out what makes sense and what's generally just an irrelevant pain.

**Comment by benedeki** [comment]
Probably most debated and maybe the only one really worth revisiting is `org.scalastyle.file.FileLineLengthChecker`. With 120 it seems we are even stricter then [`Scalastyle implementation default`](http://www.scalastyle.org/rules-0.4.0.html) which is 160.

The other I occasionally stumbled upon is `org.scalastyle.scalariform.MethodLengthChecker`. But it usually never meant a real problem to adhere to, And actually it well signaled and opportunity for better code structure.
