### ISSUE TITLE
TypeError when session expires

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#491]
## Describe the bug
When a session expires and I try to create, edit or do something more than just view I get a `typeError`.

## Screenshots
![image](https://user-images.githubusercontent.com/17467768/59673606-d896fc00-91c1-11e9-9b1d-40b77f91df69.png)

## Desktop (please complete the following information):
 - OS: macOS 10.14.5
 - Browser: Brave Version 0.65.118 Chromium: 75.0.3770.80

**Comment by benedeki** [comment]
I can confirm that after session expiration, _Menas_ behaves weirdly (Os: Windows; Browser: 75.0.3770.100 (Official Build) (64-bit))

**Comment by Zejnilovic** [comment]
if I click on to the navigation menu I get a different kind of error

![image](https://user-images.githubusercontent.com/17467768/59852502-3a489900-936f-11e9-8ebc-2d0c4847502e.png)
