### ISSUE TITLE
Rewrite DAO component

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#492]
## Description
Improve DAO classes and extract functions to separate classes. There are `var`s and duplicities in them.

**Comment by GeorgiChochov** [comment]
The `var`s aren't necessarily the biggest problem here. The `EnceladusRestDAO` and `MenasRestDAO` are a confusing split. They both interact with the same REST API.

**Comment by GeorgiChochov** [comment]
## Release Note:
#492 Rewrote the DAO module to improve maintainability of `Standardization` and `Conformance`'s communication with `Menas`
