### ISSUE TITLE
Add keytab option to menas scheduler

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#507]
## Describe the bug
We are moving away from menas credentials file to keytabs. This should be reflected here as well.

## Expected behaviour
I would still expect to be able to use both. So renaming the field but accepting either as menas credentials file is a great help for debugging and testing.

**Comment by lokm01** [comment]
Hmm and how do you want to determine if its a keytab or credentials file from the ui? Maybe we can agree on a specific extension for credentials file.

**Comment by Zejnilovic** [comment]
> Hmm and how do you want to determine if its a keytab or credentials file from the ui? Maybe we can agree on a specific extension for credentials file.

Shouldn't it always be `.properites` and `.keytab` at the end?

**Comment by lokm01** [comment]
Well... ideally....
