### ISSUE TITLE
Searching/Grouping on the side bar - Runs and Datasets

### ISSUE THREAD

**Issue by aaishaosman** [AbsaOSS/enceladus#533]
## Background
Menas Sidebar - Runs and Datasets
Currently very difficult to sift through the list to find the run or the dataset that you require.

## Feature
Add in the ability to search for the Run or Dataset by name
and/or
Add in a grouping functionality which allows for drill down when clicked for the Runs
and/or
Re-order alphabetically

## Example
Use the Runs for the drill down:
First and highlest level would be the Dataset name
Then expands to version
Then expands to run number

**Comment by GeorgiChochov** [comment]
I think this might be a duplicate of #273

**Comment by aaishaosman** [comment]
agreed...273 is the same
