### ISSUE TITLE
Searchable schema field selector

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#553]
## Background
Currently, when selecting a schema field for a conformance rule you need to scroll through the entire  schema as the selector does not provide a way to search for fields.

## Feature
It would be very useful to have a search bar at the top of the schema field selector that narrows down the options.

**Comment by lokm01** [comment]
For release notes:
[MENAS] Improved styling/UX of the local table search and implemented a search bar for schema field selectors.
