### ISSUE TITLE
Old import breaks compilation

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#563]
## Describe the bug
The last commit [677eb1e](https://github.com/AbsaOSS/enceladus/pull/558/commits/677eb1e527f833995a283c528d0db50fdc93ecec) in #558 introduced an issue and was merged before the build could be done. 
Remove `maxRetries` from `dao/src/main/scala/za/co/absa/enceladus/dao/MenasRestDAO.scala` line `35`

**Comment by GeorgiChochov** [comment]
That's what I get for being hasty with my trigger finger. Apologies.
