### ISSUE TITLE
I want to know the overview of this project 

### ISSUE THREAD

**Issue by Praveen456B** [AbsaOSS/enceladus#565]
## Describe the bug
Need to know how this application works.

## To Reproduce
Need detail explanation how menas, Standardization and conformance works.

It would be really help if you can share these details

**Comment by GeorgiChochov** [comment]
Hi there! 
Thanks for showing interest in our project, we appreciate it immensely. Unfortunately, the project is currently under heavy development and as such we are lacking the required resources to provide up to date detailed documentation beyond the [README](https://github.com/AbsaOSS/enceladus/blob/develop/README.md). However, we will be adding exhaustive documentation when the time comes. If you'd like to follow the developments on that you may subscribe to our documentation task #111.
