### ISSUE TITLE
Handling string formatting in represented by string numerics

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#58]
Handle string based formatting that source may output e.g.:
"1,000.00" = 1000.00

**Comment by lokm01** [comment]
@dwfchu @anitadsalves can you guys elaborate on this one?

**Comment by benedeki** [comment]
Verification, namely NAN check should be improved as well. (moved from #136)

**Comment by benedeki** [comment]
Properties and their eventual values to consider:
Integers
  Pattern
  Type
    Hex
    Binary
    Octal
    Decimal (default)
    
Fractal
  Decimal point
  Pattern
  Type
    Decimal Notation
    Exponent
      No pattern

**Comment by benedeki** [comment]
Class to consider for use or at for least inspiration: [`DecimalFormat`](https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html#parse(java.lang.String,%20java.text.ParsePosition))

**Comment by benedeki** [comment]
- [ ]  Understand `NumberFormat` and `DecimalFormat` classes operations
- [ ] Understand UDFs
- [ ] Implement UDFs using `NumberFormat` / `DecimalFormat` for parsing and errors
- [ ] Design needed metadata keys
- [ ] Alter `TypeParser` to use the new UDFs when unavoidable

**Comment by benedeki** [comment]
**Metadata keys, and notes on their usage:**
Details in [`NumberFormat`](https://docs.oracle.com/javase/7/docs/api/java/text/NumberFormat.html) and [`DecimalFormat`](https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html)
`base` - integral, no pattern allowed
`pattern`
`decimal_separator` - fractional, no need for pattern
`minus_sign` - no need for pattern
`patterndelimiter` - requires pattern
`percent_sign` - requires pattern
`permile_sign` - requires pattern
`infinity_value` - Float and Double, no need for pattern
`exponent_separator` - requires pattern
`zero_digit` -  no need for pattern

**Comment by benedeki** [comment]
`DecimalFormat` is little eager in parsing the strings, sometimes deducing numbers not really well represented. But for first implementation good enough.

**Comment by benedeki** [comment]
### For release notes
* Standardization: It's possible to specify patterns representing numbers for parsing input string (e.g. "1,000.123" -> 1000.123 for pattern _"#,##0.##"_ )
* Standardization: It's possible to alter some decimal symbols (like decimal separator being _","_) 
* Standardization: Whole numbers can be entered in different radix (base) then 10, for example as hexadecimals
(details for above three in documentation)
