### ISSUE TITLE
Standardization and conformance fail to use local menas-credential-file if HDFS is down

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#600]
## Describe the bug
Standardization fails when provide local path for mean credential file - at least on WIndows - with:
`Error: Option --menas-credentials-file failed when given 'C:/Users/xyz/menas-credential.properties'. Pathname /C:/Users/xyz/menas-credential.properties from C:/Users/xyz/menas-credential.properties is not a valid DFS filename.`

## To Reproduce
Run **Standardization** with parameter:
`--menas-credentials-file C:/Users/xyz/menas-credential.properties`

**Comment by Zejnilovic** [comment]
I just retested this and I came up with the conclusion that local paths do not work if there is any error with HDSF. For example, providing invalid HDFS filename (@benedeki's issue) or HDFS being unreachable altogether. If HDFS is running and there is no error checking it first, it will use the local path as instructed, as the second step. 

This is still an issue, but a different one

**Comment by Zejnilovic** [comment]
The same issue affects conformance as well.

**Comment by benedeki** [comment]
@Zejnilovic  If you have the test ready, can you please check if the suggested fix also addresses the issue you discovered?
