### ISSUE TITLE
Add OpenAPI (Swagger) docs

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#601]
## Background
Currently, the Menas REST API is undocumented.

## Feature
We should have a way to automatically generate our REST API documentation.

## Proposed Solution
1. We could use [springfox](https://github.com/springfox/springfox) to generate our OpenAPI (Swagger) documentation.

**Comment by AdrianOlosutean** [comment]
Release notes
Added swagger API documentation for the Rest API
