### ISSUE TITLE
Add enceladus_info_date_string field to Conformance output to avoid confusion with time zones

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#610]
## Background
The `enceladus_info_date` date field is normalized to UTC. That can cause confusion in case the parquet file is read in different time zone setting. The string field should decrease the uncertainty.

## Feature
Add a new field to the data frame of the type `string` and containing the date.

**Comment by aaishaosman** [comment]
will this change how the output looks in publish?

**Comment by Zejnilovic** [comment]
> will this change how the output looks in publish?

Yes, this will change add the column to the dataset. This column will be the info date in a string format. Parque doesn't handle timezones very well so if it was left in the Date format it sometimes shows "wrong" date and users might misinterpret the data and on which report date it was run.
