### ISSUE TITLE
Schema list on dataset creation

### ISSUE THREAD

**Issue by aaishaosman** [AbsaOSS/enceladus#613]
## Describe the bug
currently when creating a dataset, user needs to link a schema - the current list that comes up for a user to choose from does not show the entire list of schemas available

**Comment by GeorgiChochov** [comment]
`sap.m.Select` has a property `showSecondaryValues` which shows additional info for `sap.ui.core.ListItem`s which disables scrolling. Don't know why it does that, but it happens... @lokm01 ideas?

**Comment by lokm01** [comment]
> `sap.m.Select` has a property `showSecondaryValues` which shows additional info for `sap.ui.core.ListItem`s which disables scrolling. Don't know why it does that, but it happens... @lokm01 ideas?

I'll check

**Comment by lokm01** [comment]
I think I'll have a fix soon

**Comment by lokm01** [comment]
Can you test this in style.css

.sapMPopoverScroll > .sapUiSimpleFixFlex > .sapUiSimpleFixFlexFlexContentContainer {
  overflow-y: auto !important;
}

**Comment by GeorgiChochov** [comment]
Scroll was made visible, but the results still cut off.

**Comment by lokm01** [comment]
Model limit?
