### ISSUE TITLE
Max column length for standardisation

### ISSUE THREAD

**Issue by aaishaosman** [AbsaOSS/enceladus#615]
## Background [Optional]
Some data currently have thousands of columns - it is just the nature of the source data. Business have been advised to split the files - but this seems to still be an issue.

## Question
The older version of standardisation could handle about 800 columns before issues arise - this was also as a result of the old version of spark.
What is the current max-level of columns that the new version can accomodate before there are issues ie. on the new version of spark?

**Comment by DzMakatun** [comment]
The current version should support up to 10K columns. This is limited by Spark defaults. Upon demand, it is possible to extend this even further, but with potential performance penalties. (Related issue #165).

Having this said, splitting the files, when possible, remains a good practice.

**Comment by GeorgiChochov** [comment]
Let's consider this resolved and remember to document this.
