### ISSUE TITLE
If something takes long time to load add some "cogwheel" animation

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#623]
## Background
There might be a lot of data to be downloaded or there is just a slow connection between you and the server and then the data that is supposed to be downloaded is shown as "No Data" while downloading

## Feature
Add some cogwheel or in progress animation for things that take longer time.

**Comment by GeorgiChochov** [comment]
## For release notes
The master pages for `Dataset` `Schema` and `Mapping Table` now show a busy indicator while they are fetching data.
