### ISSUE TITLE
Dashboard tiles don't work

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#634]
## Describe the bug
Dashboard tiles don't work.
Console: `Uncaught TypeError: Cannot read property 'getCurrentPage' of undefined at h.showMaster (SplitContainer-dbg.js:1245)`

**Comment by lokm01** [comment]
How do I replicate?

**Comment by Zejnilovic** [comment]
Open Menas home page and click on any of the tiles to datasets, runs, etc.

**Comment by Zejnilovic** [comment]
Found out this is mainly the problem of the small width view where the navigation menu is hidden.
