### ISSUE TITLE
Uber JAR Standardisation and Conformance

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#64]
Provide 1 JAR artifact for both Conformance and Standardisation.
This will simplify configuration files and also reduce risk of running mismatched STD and CONF versions by users.

**Comment by yruslan** [comment]
* Agreed to move everything to `enceladus-conformance` module, at least for now.
* The purpose of the task is to make it work in a single jar. Further refactoring should be done as subsequent tasks.

**Comment by Zejnilovic** [comment]
I love the idea, but we will need to think more about how we provide parameters, otherwise, it's gonna be too much.

**Comment by yruslan** [comment]
Time spent 'in progress': 1.5 days.

**Comment by yruslan** [comment]
Release notes
Standardization and Conformance JARs are now combined in 'spark-jobs.jar'. This allows using a single JAR file for both jobs. The class names for the jobs remain the same. Note: this change requires updating helper scripts and setting the 'SPARK-JOBS-JAR' environment variable in 'enceladus_env.sh'.
