### ISSUE TITLE
Chain Standardization and Conformance when running using helper scripts

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#671]
## Background
Currently Standardization and Conformance can only br ran separately. Most of the time these 2 Spark jobs are chained. Conformance always follows Standardization.

## Feature
Provide a script that runs both jobs one by one automatically. E.g. run Conformance if Standardization is finished successfully.

This can be supported in 'client' deployment mode.

**Comment by yruslan** [comment]
Spark jobs seem not setting exit status on failure. Need to find an alternative way to check if Standardization has failed so no attempt is made to run Conformance.

**Comment by GeorgiChochov** [comment]
> Spark jobs seem not setting exit status on failure. Need to find an alternative way to check if Standardization has failed so no attempt is made to run Conformance.

Extracted to a separate task #893

**Comment by AdrianOlosutean** [comment]
I think this issue is not really needed anymore

**Comment by Zejnilovic** [comment]
Solved by #1465
