### ISSUE TITLE
Add a crontab job for cleaning up old standardized folders

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#673]
## Background
Most of the time standardized data becomes obsolete when published after conformance. Users forget to clean up standardized folders. This can be automated.

## Feature
Add a crontab job template for cleaning standardized folder periodically. The job should delete only old standardized folders. Say, if a folder is a week old it might be deleted.

**Comment by lokm01** [comment]
See also #672

**Comment by yruslan** [comment]
ToDo: Find `find ... | rm` command analogy for HDFS.

**Comment by benedeki** [comment]
This is not relevant anymore. Also wouldn't really work due to access rights.
