### ISSUE TITLE
Add more options for standardizing CSV files

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#688]
## Background
Input CSV files can
- Have an encoding other than UTF-8.
- Non-escaped quote characters inside its fields
- Escaping character for input CSVs may differ from Spark's non-standard '\'.

CSV Standard for the reference: https://tools.ietf.org/html/rfc4180
Spark does not follow the standard. In the RFC a quote is escaped as `""`, while Spark expects `\"`.

## Feature
Add Standardization command line options to fine tune encoding and escaping rules already supported by Spark.

- `charset ` (default is `UTF-8`), e.g. `.option("charset", "UTF-8")`
- `quote` (default is `"`), e.g. `.option("quote", "\"")`
- `escape` (default is `\`), , e.g. `.option("escape", "\\")`

## Proposed Solution
The corresponding command line parameters may be
- `--charset` - expects a string parameter specifying a charset. The name does not have 'csv' prefix since the option may be reused for other formats as well potentially)
- `--csv-quote` - expects a character parameter.
- `--csv-escape` - expects a character parameter.

**Comment by lokm01** [comment]
Any chance this could be made more generic for other data sources and their parameters?

**Comment by yruslan** [comment]
Something like
```
--format-options charset="UTF-8",escape=\\,quote=\"
```
?

**Comment by lokm01** [comment]
Maybe... Not sure what would be the best way :)

**Comment by yruslan** [comment]
Discussed this with @GeorgiChochov. Decided to go for specific options rather than generic ones.
- Spark is very permissive and does not complain if an option is unrecognized by a format (like `rowtag` for CSV). Typos in option names may cause an option to be ignored. Cobrix has 'pedantic' option to make Spark App throw an exception when an unknown option is specified.
Enceladus currently does not use `pedantic` since `.option("header", false)` is passed for every format, even if it is not specified in the command line. 
- Some of the options otherwise legitimate we don't want Standardization users to use. Like `dateFormat` or `inferSchema`.
