### ISSUE TITLE
Generating test data

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#75]
The generator can be a spark job which accepts a spark schema and generates an appropriate dataset.

The test data should be defined by:
- format (xml, csv, parquet, etc.)
- data types (string, int... be exhaustive)
- number of records
- number of columns
- levels of nesting (structs and arrays)
- specific and random data (we can use the schema's metadata to specify this)

This might involve the creation of a schema generation tool (there might be something out there), which can be done in a separate task if necessary.

**Comment by GeorgiChochov** [comment]
@Zejnilovic Is this still a thing? Or do we close it?

**Comment by Zejnilovic** [comment]
> @Zejnilovic Is this still a thing? Or do we close it?

I thought you wanted to give this a shot. 

 But generally, yeah, something like this would be nice.

**Comment by Zejnilovic** [comment]
Moved to [Hermes #11](https://github.com/AbsaOSS/hermes/issues/11)
