### ISSUE TITLE
Add Schema after conformance to the Dataset view

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#763]
## Background
We currently possess transitive schema when creating conformance rules but we do not show this scheme anywhere.

## Feature
Add a tab `Schema after conformance` (the name is WIP) or add a switch to the current schema to see how the schema will look at the end of all conformance rules.

## Bonus points
Be able to export the final schema - is there a use case of this? Will someone need it?

**Comment by Zejnilovic** [comment]
Possible duplicate of #763

**Comment by dk1844** [comment]
Release notes:
Menas UI now displays projected after-conformance schema for datasets.

**Comment by dk1844** [comment]
Released notes:
Menas UI now displays projected after-conformance schema for datasets.
