### ISSUE TITLE
Generalize delimiter handling in convenience scripts

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#764]
## Background
The current processing of csv delimiters in convenience  scripts has a special case for a single whitespace. It also limits the delimiter to be a single special character, (or multiple non-special characters). 

scripts/bash/run_enceladus.sh     

```
if [[ "$2" == " " ]]; then       
DELIMITER="' '"     
else       DELIMITER="\\$2"   

```
## Feature
In order to be ready for non-standard csv delimiters it would be good to generalize this.

## Example [Optional]
Multiple whitespaces, combination of special characters.

## Proposed Solution [Optional]
`DELIMITER=\'"${2}"\'`

**Comment by GeorgiChochov** [comment]
Had to look this up but it turns out Spark does not allow multiple chars to be used as a delimiter, and in general `csv` and other delimited data formats do not allow for this use case.
