### ISSUE TITLE
Spark jobs fail to re-login tom Menas if session expires

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#765]
## Describe the bug
This bug is reported by @DzMakatun.

Currently, Enceladus Spark jobs use DAO for accessing Menas's REST API. The first step to access the API is authentication. If it is succeeded a session is established. But jobs can run longer than session expiration time. So DAO should re-authenticate if the session expires.

However, re-authentication happens only if 401 (Unauthorized) status code is received. Enceladus won't authenticate if 403 (Forbidden) is encountered.

## To Reproduce
Run a Standrdization or Conformance job that lasts more than half a hour.

## Expected behaviour
Standardization and Conformance jobs should re-authenticate if 403 status code is received.

## Additional context
```
19/08/05 12:48:25 ERROR dao.MenasRestDAO$: RESPONSE: HTTP/1.1 403  - {"timestamp":"2019-08-05T10:48:25.607+0000","status":403,"error":"Forbidden","message":"Forbidden","path":"/menas/api/runs/updateRunStatus/dea3e466-947d-4ed2-8b19-3f72cffcddff"}
19/08/05 12:48:25 ERROR EventListenerMenas: Unable to update status of a run object (dea3e466-947d-4ed2-8b19-3f72cffcddff) in the database
Exception in thread "main" org.apache.spark.SparkException: Job 1 cancelled because SparkContext was shut down
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:820)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:818)
```

**Comment by GeorgiChochov** [comment]
TIL: Don't rush things even under pressure. There is an additional underlying bug [here](https://github.com/AbsaOSS/enceladus/blob/develop/dao/src/main/scala/za/co/absa/enceladus/dao/EnceladusRestDAO.scala#L187) and [here](https://github.com/AbsaOSS/enceladus/blob/develop/dao/src/main/scala/za/co/absa/enceladus/dao/MenasRestDAO.scala#L136) that is unaddressed, which actually fails the retry even after successful reauthentication.
I'll open an additional PR, and we'll merge it after additional testing.
