### ISSUE TITLE
Creation of dataset/mapping table sends all schema versions as payload

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#769]
## Describe the bug
Creation of dataset/mapping table sends all schema versions as payload

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Create dataset
2. Link schema with more than one version
3. Look at the create rest call

## Expected behaviour
Send only the used one

**Comment by GeorgiChochov** [comment]
Applies to edits as well
