### ISSUE TITLE
Duplicated run objects after standardization

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#780]
## Describe the bug
After standardization two run documents are created with the same start time and sequential run ids:
- the first run (run id = i) document contains the checkpoints from the _INFO file only and has a status "running"
- the second run (run id =  i+1 ) document contains the proper data and checkpoints 

The problem dates back at leas to August 1st 2019

## To Reproduce
- The problem can be observed in Menas UI at asgard in 25600cols dataset (dataset -> runs)
- To reproduce the problem, execute standardization and check: 
dataset -> runs in Menas 
or 
the documents in the  run collection in the mongodb

## Expected behaviour
The first object is incorrect. Only the second object containing the proper checkpoint data and statuses should be created.

## Screenshots

![Screen Shot 2019-08-07 at 10 39 05](https://user-images.githubusercontent.com/8556576/62608437-1f6ebb80-b900-11e9-8c8e-a6fadd691510.png)

**Comment by yruslan** [comment]
This is a regression from #454
Atum can call plugin's `EventListenerMenas.onLoad()` more than once.
