### ISSUE TITLE
object EnceladusRestDAO uses vars

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#815]
## Describe the bug
`object EnceladusRestDAO` uses `var`s in the code. That is very suspicious at least and can probably cause some issues. Should be refactored to avoid the `var`s.

## To Reproduce
Noticed cases:
```
var _userName
var _sessionCookie
var _csrfToken
```

**Comment by Zejnilovic** [comment]
I would call this duplicate. More in #492
If you agree please mark and close.

**Comment by yruslan** [comment]
This module is currently under complete rewrite by Georgi. I doubt there will be anything to refactor in DAO after he is done 😄

**Comment by benedeki** [comment]
Thanks guys. Closing
