### ISSUE TITLE
Conformance rule output column should be reflected in schema 

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#82]
When adding a new conformance rule, the schema presented in any input column should reflect the dataset's schema as it will appear after all changes from preceding rules have been applied to it (i.e., the original schema + all output columns - all dropped columns).

**Comment by Zejnilovic** [comment]
There is an issue found after extraction of components. Now the schema isn't reflected, sometimes only part of it. Needs more look into

**Comment by GeorgiChochov** [comment]
Added #461 for further improvements.
