### ISSUE TITLE
Conformance rule validation

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#83]
When adding/editing conformance rules through the Menas UI, there should be front-end validation as well as back-end validation. This includes checking that required fields are populated and that input columns exist in the dataset's schema (as per #82).

**Comment by Zejnilovic** [comment]
First validation. Output Column Name cannot have one of these  " ,;{}()\n\t=". Affected rules are:

- CastingConformanceRule
- ConcatenationConformanceRule
- LiteralConformanceRule
- MappingConformanceRule
- NegationConformanceRule
- SingleColumnConformanceRule
- SparkSessionConfConformanceRule
- UpperCaseConformanceRule

**Comment by Zejnilovic** [comment]
Output column has to have the same parent

**Comment by Zejnilovic** [comment]
There should be a warning that `UpperCaseConformanceRule` is going to turn the field into a string.

**Comment by Zejnilovic** [comment]
`CastingConformanceRule` gives `null` on other default value if it cannot cast the source to the particular type.

We should warn/stop user if the current casting rule is going to produce a null.

**Comment by GeorgiChochov** [comment]
I'll create additional tasks for the further validation and close this issue afterwards.

**Comment by GeorgiChochov** [comment]
> There should be a warning that `UpperCaseConformanceRule` is going to turn the field into a string.

#554

**Comment by GeorgiChochov** [comment]
> `CastingConformanceRule` gives `null` on other default value if it cannot cast the source to the particular type.
> 
> We should warn/stop user if the current casting rule is going to produce a null.

#555

**Comment by Zejnilovic** [comment]
> Output column has to have the same parent

#552

**Comment by GeorgiChochov** [comment]
Thanks for bringing these up, creating the tasks and helping break this down, @Zejnilovic !
