### ISSUE TITLE
Add release notes tab in form of posts to the gh-pages

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#831]
## Background
Use the jekyll documentation template and add posts field for release notes.
Maybe check if they are the right thing to use

## Feature
Create release notes field in the documentation.

**Comment by GeorgiChochov** [comment]
## Release v1.1.0
# Menas Improvements
#337 Validate HDFS Paths for special characters.
#446 Scheduling can now be suspended and resumed. Also allows datasets to be `run once` ability via the UI or REST API.
#447 Continuous migration of data from old Menas to new.
#573 Creating entities with special characters in the name show a more appropriate message. 
#734 Monitoring now shows if controls for a `Run` don't match across checkpoints. 
#772 Aligned order of inputs in `Drop Rule` with other `Conformance Rules`.
#777 Better error report on failure to upload schema.
#793 Creating a `Schema` with forbidden characters no longer hangs on pressing save.
#826 Environment name is now displayed in the header.

# Standardization Improvements
#420 Nullable columns will no longer be assigned a default when unable to standardize to a particular type. Instead they will be `null`.
#797 Raw format of the standardized dataset is tracked in `_INFO` file and available in the `Run` information in Menas.

# Conformance Improvements
#770 Casting to `Timestamp` now has validation.
#773 `Negation Rule` now applicable to `Boolean` type (not just `Numeric` types).

# Scripts Improvements
#806 Helper scripts now properly get principal from keytab for service users .
#850 Fixed typo in standardization script name.

# Comparison Job Improvements
#835 Comparison Job can now read in XML.
