### ISSUE TITLE
Upon schema upload failure provide hint what went wrong

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/enceladus#865]
## Background
When one tries to upload  a schema and it fails, following message appears: _Failed to get the detail of the Schema. Please wait a moment and try reloading the application_
That doesn't really help the user to figure out, what's wrong.

## Feature
Provide some information what went wrong and where in the uploaded file.

**Comment by GeorgiChochov** [comment]
Duplicate of #777

**Comment by benedeki** [comment]
Duplicate of recently closed #777. Closing
