### ISSUE TITLE
Enforce 'source' and 'raw' checkpoints when starting Standardization

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#873]
## Background
Currently, Standardization will run independently of which checkpoints are in the INFO file that comes with raw data. This complicates INFO files and Run object analysis downstream.

## Feature
Enforce the existence of 'source' and 'raw' checkpoints by refusing to run Standardization on data that do not have these checkpoints.

**Comment by AdrianOlosutean** [comment]
Is this the same as #1322 ?
