### ISSUE TITLE
Ensure Oozie compatibility with secured, kerberized, HDP clusters

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#883]
## Background
For environments, where it's not easy or possible to add specific sharelibs for a given action into system libpath, we may wanna specify our own libpath location.

Additionally, there are different types of issues when trying to run on a kerberized cluster (namely around permissions etc).

**Comment by GeorgiChochov** [comment]
@lokm01 can you write some release notes for this and close it?

**Comment by GeorgiChochov** [comment]
> @lokm01 can you write some release notes for this and close it?

Nevermind, found them in the PR:
## For release notes:

Implemented integration with kerberized Oozie through impersonation and additional configuration parameters for flexibility of use
