### ISSUE TITLE
Mapping Table Conformance rule shows bad join condition path

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#890]
## Describe the bug
Mapping Table Conformance rule shows bad join condition path. 

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Make a mapping conformance rule
2. Check the Join Conditions
3. On the right side should be the name of the mapping table, but there is a name of the dataset

## Expected behaviour
On the right side, we should show the name of the mapping table

## Screenshots
![image](https://user-images.githubusercontent.com/17467768/64591231-9e488f80-d3a9-11e9-8275-57cea6a43892.png)

## Additional info
Set as low, because this bug is only a small visual one. If edited, it shows everything properly and conformance runs as intended.

**Comment by GeorgiChochov** [comment]
Set as medium, because while not breaking any functionality and not urgent, it is still a pretty important issue.

**Comment by GeorgiChochov** [comment]
## For release notes
Fixed visual bug in conformance rules where the `Mapping Rule` was showing misleading join conditions by displaying the dataset name on both sides of the join. The join conditions are now displayed as `dataset.column - mapping_table.column`
