### ISSUE TITLE
Mapping rule with literal in the join condition (may) throw a cross join error

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#892]
## Describe the bug
Since Spark 2.3.1, joins (in our case left_outer) throw a cartesian product exception if one part of the join condition is a column previously produced by a literal rule.

The behaviour of this is questionable as it seems that catalyst isn't able to "reduce" the logical plan in certain cases.

**Comment by lokm01** [comment]
Seems related to https://issues.apache.org/jira/browse/SPARK-24839

**Comment by GeorgiChochov** [comment]
For release notes:
Mapping rules can now safely join on columns created by a literal rule. (currently just a workaround which will be refined in #895)
