### ISSUE TITLE
Make Spark persist level configurable

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#899]
Currently we're using cache everywhere.

We should change these to persist and make the level configurable.

See https://data-flair.training/blogs/apache-spark-rdd-persistence-caching/

This is quite important for jobs (namely standardization) ingesting very large files. In those cases, you'd like to change the persist level to X_SER to minimize the size of data in memory & amount of data spilled and read from disk.

**Comment by yruslan** [comment]
For release notes: Add an option to control the storage level of dataframe persistence. This could help to fine-tune Standardization and Conformance jobs for specific datasets.
