### ISSUE TITLE
Allow processing empty datasets

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#909]
## Describe the bug
Currently, Standardization fails if the output is empty. This often happens when a rowtag is incorrectly specified. But if the source dataset is empty the output should legitimately be empty as well. 

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Create an empty raw folder and put an info file into it.
2. Run Standardization.

## Expected behavior
Standardization and Conformance should work on an empty dataset.

The fix is needed for Standardization. Conformance should already work fine, just need to confirm.

**Comment by Zejnilovic** [comment]
Closed by #911 - Added a check if all checkpoints are zero then empty output is allowed. Otherwise, throw an error.

**Comment by GeorgiChochov** [comment]
For release notes:
Allow standardization and conformance to process empty datasets. Non-empty datasets which are read incorrectly (e.g., `xml` with a wrong `row tag`) will still fail the run if their source/raw checkpoint says they are supposed to have more than 0 records.
