### ISSUE TITLE
JWT stateless authentication

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#92]
In order to provide a stateless REST API we should move to [JWT](https://jwt.io/) authentication rather than using session cookies. 
- Session cookies are vulnerable to [CSRF](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)), which is usually prevented with an anti-CSRF token sent along with the session cookie, in a response header or the response body, to be sent along with the cookie on every request, so the cookie alone is not enough to hijack a session. The server needs to be aware of both the session and the CSRF token, which makes it stateful.
- JWTs are basically a server-signed token containing all necessary auth information. This allows the server to be entirely stateless and therefore scalable. Normally, they are not stored in cookies, which entirely obviate the need for CSRF protection and makes them perfect for REST APIs.

However, this security comes at the cost of user convenience, since the JWT is not stored in a cookie this means that the user will have to log in on every refresh or new tab. We don't want to sacrifice this convenience.
This brings us back to storing cookies and CSRF vulnerabilities. We should store the JWT in a cookie (with `http-only` and `secure` flags) and, our stateless CSRF protection can work as follows:

### Server sends successful login response:
- create a CSRF token
- create a JWT with the CSRF token embedded
- send it the CSRF token in a response header along with the JWT

### REST client
- stores CSRF token and JWT in memory
- sends them as a pair on every request

### UI client
- stores CSRF token in local/session storage (in order to be accessible through other tabs) 
- stores JWT as a cookie
- sends both as a pair on every request

### Server receives request
- decrypts JWT
- checks CSRF token from JWT matches CSRF token from request header 

This will allow secure communication between Enceladus and Menas (#86), as well as secure communication between the Menas back-end and front-end, without decreasing user convenience.

**Comment by benedeki** [comment]
Afaik JWT is created with some expiry timestamps (e.g. valid for 10 minutes).
How will we address that expiry issue?
We can either resend a new JWT with each response to Server request. Or clients have to handle re-authentication in case the JWT expires. In either case i's some extra effort on Client side.

Or is it possible the JWT is not expiring (or reaaaaaly in the future), and then the Server handles the validity of the JWT within memory (removal  in case of blacklisting or if it wasn't used for certain time)?

**Comment by GeorgiChochov** [comment]
> Afaik JWT is created with some expiry timestamps (e.g. valid for 10 minutes).
> How will we address that expiry issue?
> We can either resend a new JWT with each response to Server request. Or clients have to handle re-authentication in case the JWT expires. In either case i's some extra effort on Client side.
> 
> Or is it possible the JWT is not expiring (or reaaaaaly in the future), and then the Server handles the validity of the JWT within memory (removal in case of blacklisting or if it wasn't used for certain time)?

Good point, I was thinking of giving the token a short (15-20) minutes lifespan and returning a new token on each request. In any case we need this to be handled client-side.

**Comment by Zejnilovic** [comment]
> > Afaik JWT is created with some expiry timestamps (e.g. valid for 10 minutes).
> > How will we address that expiry issue?
> > We can either resend a new JWT with each response to Server request. Or clients have to handle re-authentication in case the JWT expires. In either case i's some extra effort on Client side.
> > Or is it possible the JWT is not expiring (or reaaaaaly in the future), and then the Server handles the validity of the JWT within memory (removal in case of blacklisting or if it wasn't used for certain time)?
> 
> Good point, I was thinking of giving the token a short (15-20) minutes lifespan and returning a new token on each request. In any case we need this to be handled client-side.

I remember a project where, single page app, that checked for token TTL time every X minutes, and if it got lower then 5 min, it asked the server to issue a new one using the old one. RestAPI had to call auth again.

So server had an endpoint `re-issue` or something like that. And it could be reissued for 10 hours or so, then the user needed to use credentials again.

**Comment by GeorgiChochov** [comment]
## For Release notes
Menas authentication is now stateless, using JWT.
