### ISSUE TITLE
Add a REST API method to check if the server is up and running

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#933]
## Background
Reported by **Aliaksei**

Currently, all API calls require logging in. It would be helpful for external monitoring tools to be able to check the status of the server.

## Feature
Add an API call to check if a server is up and running.
The call should not require the caller to be logged in.

## Additional Context
This is me being creative, not sure if it makes sense. But maybe this method could as well report status on:
* Uptime
* CPU usage (similar to what is reported by `uptime` in Linux)
* LDAP connectivity
* HDFS connectivity
* Spline connectivity
* MongoDB connection health
* Free memory and disk space maybe.

**Comment by GeorgiChochov** [comment]
At least some of this will be provided by `Spring Boot Actuator` #884. We can expand it to cover your other ideas as well (I like them).

**Comment by GeorgiChochov** [comment]
I think we can consider this done by #884
