### ISSUE TITLE
Empty body is sent on the initial Run creation via a POST request

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#945]
## Describe the bug
When Standardization sends a POST request to Menas for the initial creation of a run object an empty JSON body is sent.

For some reason, it seems runs are not serialized and no exception is thrown.

## To Reproduce
Run a Standardization job.

## Expected behaviour
  - [x] Any objects sent via a POST request should be serialized as JSONs.
  - [x] If an empty (not deserialized) body is sent, Menas should return status of 400 (Bad request) instead of 201.

## Log

Here is an example that shows that a null run is created successfully.
```
19/10/01 13:18:57 INFO RestClient: POST - URL: http://localhost:8080/menas/api/runs
19/10/01 13:18:57 INFO RestClient: POST - BODY: Run(None,0,Cobol1,2,SplineReference(application_1569914102171_0123,),01-10-2019 11:18:57 +0000,RunStatus(running,None),ControlMeasure(ControlMeasureMetadata(Test1,CZ,Snapshot,CobolFile.bin,G,1,25-02-2019,Map()),None,List(Checkpoint(Source,25-02-2019 08:00:00,25-02-2019 08:00:00,Source,1,List(Measurement(recordCount,controlType.Count,id,4964))), Checkpoint(Raw,25-02-2019 08:00:00,25-02-2019 08:00:00,Raw,2,List(Measurement(recordCount,controlType.Count,*,4964))))))
19/10/01 13:18:57 INFO RestClient: Response (201): {"uniqueId":"3553a588-3cff-44a9-a91c-9e11380c2121","runId":5,"dataset":null,"datasetVersion":0,"splineRef":null,"startDateTime":null,"runStatus":null,"controlMeasure":null}
```

**Comment by GeorgiChochov** [comment]
This was introduced in #492

**Comment by GeorgiChochov** [comment]
It seems that the `RestTemplate` has a series of default `HttpMessageConverter`s and it works with the first appropriate one to serialize the content, however, it has a default `MappingJackson2HttpMessageConverter`, which doesn't know how to handle scala classes. When we add our own (scala-capable one) it is appended to the end of the list and ignored. I've added a way to fix this but in addition I think it's better to explicitly serialize and log what we are sending.
