### ISSUE TITLE
Naming of Spark jobs

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#950]
## Background
In the current Enceladus version all the jobs have names either "Standardization" or "Conformance". In the old version the names were more explicit and include dataset name, info date and etc.
 
Having more details in the job names simplifies search in Spark history. Allowing some custom naming would be helpful for debugging/performance evaluation too. For example, including the number of executors/cores/memory would allow to compare performance directly from the top level view in YARN and Spark history.  

Otherwise, dataset names and etc. are not searchable. Debugging and performance monitoring requires joining  Spark history data with Menas runs. 

## Question
Are there any restrictions to make the jobs names more explicit/custom? Anything related to Oozie?

**Comment by DzMakatun** [comment]
@lokm01 @yruslan

**Comment by yruslan** [comment]
I vaguely remember something that required the Spark context to be passed to the command line parser. For this to work, the Spark context should already exist. And until the command line is parsed the dataset name, version and date are unknown. So that's why jobs now have the same names.

**Comment by Zejnilovic** [comment]
Weirdly, we set `appName` to "Standardization" in StandardizationJob.scala line [129](https://github.com/AbsaOSS/enceladus/blob/84295a26f2cc8c345772e4992968bbc0e0ee91f8/standardization/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala#L129), but hadoop cluster shows it as `za.co.absa.enceladus.standardization.StandardizationJob`.

All this can be overwritten by `--conf spark.app.name=AwesomeName`

**Comment by lokm01** [comment]
Spark submit has `--name` option, which configures `spark.app.name`

That's probably the best approach.

Oozie passes that too `s"Menas Schedule Conformance ${ds.name} (${ds.version})"`

**Comment by DzMakatun** [comment]
@lokm01 @Zejnilovic
Yarn and spark history actually show "Standardization"
 --name and --conf spark.app.name=AwesomeName (or --conf "spark.app.name=AwesomeName") options do not work, because StandardizationJob.scala line 129 overrides it

```
  private def obtainSparkSession(): SparkSession = {
    val spark = SparkSession.builder()
      .appName("Standardisation")
```

**Comment by DzMakatun** [comment]
@yruslan Maybe it is possible to set the job name in the convenience script using -name and provided dataset/infodate/version? And then remove name override in the Spark job itself?
 Also, convenience script may have an option --custom-job-name. The use-case could be: ----custom-job-name performanceTest-2executors-1core

**Comment by yruslan** [comment]
I'm not sure what is the best approach here. It looks like this couldn't be fixed without a breaking change.
@DzMakatun, if the override in the code (`.appName("Standardisation")`) is removed and no `--name` option provided, how the job will behave?

**Comment by yruslan** [comment]
## For release notes
Standardization and Conformance Spark application names now contain an Enceladus version, a dataset name, a dataset version, a report date, and a report version. This makes it easier to distinguish in a cluster resource management tool which jobs are running.
