### ISSUE TITLE
Users getting unexpectedly shited values in timestamp fields after standardization

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#951]
## Describe the bug
Users getting unexpectedly shited values in timestamp fields after standardization

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Set up standardization task that includes a timestamp in the schema
2. the timestamp should have no time zone specified (not in _pattern_ nor in metadata field _timezone_)
3. Run standardization
4. Check output in a session of local time-zone. Timestamp is shifted, while it's not expected

**Comment by benedeki** [comment]
The hotfix #954 addresses the imminent issue, the users are facing, that their dates are shifted incorrectly unless they specify the time zone for all timestamp fields in all schemas.

It **doesn't** address the issue, that if the `timezone` configuration is changed, weird things my start to happen with timestamp standardizations.

**Comment by benedeki** [comment]
The original bug was cloned into #963 and this one rewritten to correspond to the fix that was actually provided.
