### ISSUE TITLE
Use RESTful HTTP endpoints in Menas API

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#966]
## Background
Currently, the Menas API has endpoints specified as verbs (`.../create`, `.../edit`), this does not fit a RESTful API.

Also, correct return codes should be used (e.g. /edit returns now `201 Created`).

## Feature
The endpoints for a resource should be consistent while the HTTP method determines the operation performed on the resource.

## Example [Optional]
`GET .../dataset/list` -> `GET .../dataset`
`POST .../dataset/create` -> `POST .../dataset`
`POST .../dataset/x/y/edit` -> `PUT .../dataset/x/y`
`POST .../dataset/x/y/disable` -> `DELETE .../dataset/x/y`

**Comment by benedeki** [comment]
Part of #1693
