### ISSUE TITLE
Exclude metadata when measuring input/output sizes

### ISSUE THREAD

**Issue by DzMakatun** [AbsaOSS/enceladus#968]
## Background [Optional]
Aside from data, the directories contain the following files:
RAW: 
    _INFO       \~1kB

STD:  
   _LINEAGE \~120kB
   _INFO       \~2kB 
   _SUCESS =0B

This introduces a significant error when small files are processed (e.g. 100kB - 1 MB, which is quite often). It skews performance analysis for small files.  For example, std_size_ratio may become more than 100%. 

## Question
Is it possible to exclude metadata files when measuring input/output sizes?

**Comment by DzMakatun** [comment]
@yruslan

**Comment by yruslan** [comment]
Definitely. Good spot!

**Comment by yruslan** [comment]
For release notes: add metadata for input and output data sizes. These are similar to input and output directory sizes but do not include hidden files (_INFO, _LINEAGE, etc).
