### ISSUE TITLE
Arrays get reordered during conformance

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#98]
It seems like during array transformations, exploded data can get shuffled around and collapsed in any order. The data in arrays should maintain its indexed position throughout the entire run.

**Comment by yruslan** [comment]
Since conformance rules are now switching to using transform() for arrays, this issue is relevant only to the mapping rule. And only if we decide to use explode+join in the mapping rule.

**Comment by lokm01** [comment]
This is not a bug, but rather a data issue with the given mapping table.

**Comment by lokm01** [comment]
Will provide more details internally
